/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-11-30 06:18:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backoffice.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import egovframework.com.cmm.LoginVO;
import java.util.List;
import java.util.Map;

public final class top_005finc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

LoginVO loginVO = (LoginVO)session.getAttribute("LoginVO");
if(loginVO == null ){
	
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tlocation.href=\"/backoffice/login.do\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
        
}else{ 
	
	
	
	
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("<div class=\"header_wrap\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<ul id=\"header\" class=\"contents\">\r\n");
      out.write("        \t<li class=\"logo\"><h1>경륜경정 스마트 입장시스템</h1></li>\r\n");
      out.write("        \t<li class=\"toggle\"><a href=\"#\" onclick=\"toggleNav()\" class=\"menu\"></a></li>\r\n");
      out.write("        \t<li class=\"logo1\"><img src=\"/resources/img/logo1.png\" alt=\"\"></li>\r\n");
      out.write("        \t<li class=\"member\"><img src=\"/resources/img/login.png\" alt=\"\"><span>");
      out.print(loginVO.getAdminId() );
      out.write("</span> 님</li>\r\n");
      out.write("      \t</ul>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--top //-->\r\n");
      out.write("    <!--// menu list -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() { \r\n");
      out.write("    \t   fn_menuCreate();\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction fn_menuCreate (){\r\n");
      out.write("\t\tvar url = window.location.pathname;\r\n");
      out.write("\t\tvar menu = uniAjaxReturn(\"/backoffice/inc/user_menu.do\", \"POST\", false, null,  \"lst\");\r\n");
      out.write("\t\tfor (var i in menu){\t\r\n");
      out.write("\t\t\t if  (menu[i].level == \"2\"){\r\n");
      out.write("\t\t\t\t var ul_list = $(\"#ul_leftMenu\"); //ul_list선언\r\n");
      out.write("\t\t\t\t ul_list.append(\"<li id='menu_li_\"+menu[i].menu_no+\"'></li>\");\r\n");
      out.write("\t\t\t\t $(\"#menu_li_\"+menu[i].menu_no+\"\").append(\"<button type='button' onClick='fn_menuClick(\"+menu[i].menu_no+\")' class='sub_menu' id='menu_bn_\"+menu[i].menu_no+\"'>\"+menu[i].menu_nm+\"</button>\");\r\n");
      out.write("\t\t\t\t $(\"#menu_bn_\"+menu[i].menu_no +\"\").after(\"<div id='menu_dv_\"+menu[i].menu_no+\"' class='panel'></div>\");\r\n");
      out.write("\t\t\t }else {\r\n");
      out.write("\t\t\t\t var dv_list = $(\"#menu_dv_\"+menu[i].upper_menu_no+\"\"); //ul_list선언\r\n");
      out.write("\t\t\t\t var active = \"\";\r\n");
      out.write("\t\t\t\t if (menu[i].url == url){\r\n");
      out.write("\t\t\t\t\t active = \"active\";\r\n");
      out.write("\t\t\t\t\t fn_menuClick(menu[i].upper_menu_no);\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t\t dv_list.append(\"<a href='\"+menu[i].url+\"' id='\"+menu[i].menu_no+\"' class=\"+active+\">\"+menu[i].menu_nm+\"</a>\");\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\ttoggleNav();\r\n");
      out.write("\t}\r\n");
      out.write("\t/* menu */\r\n");
      out.write("\tfunction toggleNav() {\r\n");
      out.write("\t    if (document.getElementById(\"mySidenav\").style.width == \"0\") {\r\n");
      out.write("\t        closeNav(); \r\n");
      out.write("\t    } else { \r\n");
      out.write("\t        openNav(); \r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction openNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"200px\";\r\n");
      out.write("\t  document.getElementById(\"contents\").style.marginLeft = \"200px\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction closeNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"0\";\r\n");
      out.write("\t  document.getElementById(\"contents\").style.marginLeft= \"0\";\r\n");
      out.write("\t}\r\n");
      out.write("    function fn_menuClick(id){\r\n");
      out.write("    \tvar acc = document.getElementsByClassName(\"sub_menu\");\r\n");
      out.write("    \tvar i;\r\n");
      out.write("    \tfor (i = 0; i < acc.length; i++) {\r\n");
      out.write("    \t\tacc[i].classList.toggle(\"toggle_off\");\r\n");
      out.write("    \t\tvar panel = acc[i].nextElementSibling;\r\n");
      out.write("    \t\tpanel.style.display = \"none\";\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \tvar block_pn = ($(\"#menu_dv_\"+id).prop('style') == \"block\") ? \"display:none\" : \"display:block\";\r\n");
      out.write("    \t$(\"#menu_bn_\"+id).prop('class','sub_menu toggle_on');\r\n");
      out.write("    \t$(\"#menu_dv_\"+id).prop('style', block_pn); \r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("\t\t<ul id=\"ul_leftMenu\">\r\n");
      out.write("\t\t\t                                \r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- menu list //-->\r\n");
      out.write("</div>\r\n");
      out.write(" ");

     }
 
      out.write('\r');
      out.write('\n');
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
