/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-11-30 09:06:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backoffice.bld;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class seasonList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no;\" />\r\n");
      out.write("    <title>경륜경정 스마트입장 관리자</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/reset.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/paragraph.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/toggle.css\">\r\n");
      out.write("    <script src=\"/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/bpopup.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- datepicker-->\r\n");
      out.write("    <script src=\"/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("\t\tjQuery.browser = {};\r\n");
      out.write("\t\t(function () {\r\n");
      out.write("\t\t    jQuery.browser.msie = false;\r\n");
      out.write("\t\t    jQuery.browser.version = 0;\r\n");
      out.write("\t\t    if (navigator.userAgent.match(/MSIE ([0-9]+)\\./)) {\r\n");
      out.write("\t\t        jQuery.browser.msie = true;\r\n");
      out.write("\t\t        jQuery.browser.version = RegExp.$1;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t})();\r\n");
      out.write("\t</script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/jquery-ui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/jqgrid/src/css/ui.jqgrid.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/src/i18n/grid.locale-kr.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("     .ui-jqgrid .ui-jqgrid-htable th div{\r\n");
      out.write("\t\toutline-style: none;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t }\r\n");
      out.write("     .ui-jqgrid tr.jqgrow {\r\n");
      out.write("\t\toutline-style: none;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- GUI js/css -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resources/js/modernizr.custom.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/js/classie.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/js/dragmove.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/js/common.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/js/back_common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.cbp-spmenu {\r\n");
      out.write("\t\t\tbackground: #3670c5;\r\n");
      out.write("\t\t\tposition: fixed;\r\n");
      out.write("\t  \t}\r\n");
      out.write("      \t.cbp-spmenu a {\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\tfont-size: 1.1em;\r\n");
      out.write("\t\t\tfont-weight: 300;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.cbp-spmenu a:active {\r\n");
      out.write("\t\t\tbackground: #afdefa;\r\n");
      out.write("\t\t\tcolor: #47a3da;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.cbp-spmenu-right {\r\n");
      out.write("\t\t\tright: -1700px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.cbp-spmenu-right.cbp-spmenu-open {\r\n");
      out.write("\t\t\tright: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.cbp-spmenu-vertical {\r\n");
      out.write("\t\t\twidth: 1700px;\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\ttop: 0;\r\n");
      out.write("\t\t\tz-index: 1000;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.cbp-spmenu-push {\r\n");
      out.write("\t\t\toverflow-x: hidden;\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tleft: 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.cbp-spmenu-push-toright {\r\n");
      out.write("\t\t\tleft: 840px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.cbp-spmenu,\r\n");
      out.write("\t\t.cbp-spmenu-push {\r\n");
      out.write("\t\t\t-webkit-transition: all 0.3s ease;\r\n");
      out.write("\t\t\t-moz-transition: all 0.3s ease;\r\n");
      out.write("\t\t\ttransition: all 0.3s ease;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.drag {\r\n");
      out.write("            -webkit-transition: all 150ms ease-out;\r\n");
      out.write("            -moz-transition: all 150ms ease-out;\r\n");
      out.write("            -o-transition: all 150ms ease-out;\r\n");
      out.write("            transition: all 150ms ease-out;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/paragraph_new.css\">\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() { \r\n");
      out.write("\t\t   jqGridFunc.setGrid(\"mainGrid\");\r\n");
      out.write("\t\t   var clareCalendar = {\r\n");
      out.write("\t\t   monthNamesShort: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],\r\n");
      out.write("\t\t   dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'],\r\n");
      out.write("\t\t   weekHeader: 'Wk',\r\n");
      out.write("\t\t   dateFormat: 'yymmdd', //형식(20120303)\r\n");
      out.write("\t\t   autoSize: false, //오토리사이즈(body등 상위태그의 설정에 따른다)\r\n");
      out.write("\t\t   changeMonth: true, //월변경가능\r\n");
      out.write("\t\t   changeYear: true, //년변경가능\r\n");
      out.write("\t\t   showMonthAfterYear: true, //년 뒤에 월 표시\r\n");
      out.write("\t\t   buttonImageOnly: true, //이미지표시\r\n");
      out.write("\t\t   buttonText: '달력선택', //버튼 텍스트 표시\r\n");
      out.write("\t\t   buttonImage: '/resource/img/invisible_image.png', //이미지주소\r\n");
      out.write("\t\t   yearRange: '2021:2099' //1990년부터 2020년까지\r\n");
      out.write("\t       };\t       \r\n");
      out.write("\t\t   $(\"#seasonStartDay\").datepicker(clareCalendar);\r\n");
      out.write("\t\t   $(\"#seasonEndDay\").datepicker(clareCalendar);\r\n");
      out.write("\t\t   $(\"img.ui-datepicker-trigger\").attr(\"style\", \"margin-left:3px; vertical-align:middle; cursor:pointer;\"); //이미지버튼 style적용\r\n");
      out.write("\t\t   $(\"#ui-datepicker-div\").hide(); //자동으로 생성되는 div객체 숨김\r\n");
      out.write("\t });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    var jqGridFunc  = {\r\n");
      out.write("    \t\tsetGrid : function(gridOption){\r\n");
      out.write("    \t\t\tvar grid = $('#'+gridOption);\r\n");
      out.write("    \t\t    var postData = {\"pageIndex\": \"1\"};\r\n");
      out.write("    \t\t    grid.jqGrid({\r\n");
      out.write("    \t\t    \turl : '/backoffice/bld/seasonListAjax.do' ,\r\n");
      out.write("    \t\t        mtype :  'POST',\r\n");
      out.write("    \t\t        datatype :'json',\r\n");
      out.write("    \t\t        \r\n");
      out.write("    \t\t        ajaxGridOptions: { contentType: \"application/json; charset=UTF-8\" },\r\n");
      out.write("    \t\t        ajaxRowOptions: { contentType: \"application/json; charset=UTF-8\", async: true },\r\n");
      out.write("    \t\t        ajaxSelectOptions: { contentType: \"application/json; charset=UTF-8\", dataType: \"JSON\" }, \r\n");
      out.write("    \t\t       \r\n");
      out.write("    \t\t        postData :  JSON.stringify( postData ),\r\n");
      out.write("    \t\t        jsonReader : {\r\n");
      out.write("\t   \t\t             root : 'resultlist',\r\n");
      out.write("\t   \t\t             \"page\":\"paginationInfo.currentPageNo\",\r\n");
      out.write("\t   \t\t             \"total\":\"paginationInfo.totalPageCount\",\r\n");
      out.write("\t   \t\t             \"records\":\"paginationInfo.totalRecordCount\",\r\n");
      out.write("\t   \t\t             repeatitems:false\r\n");
      out.write("   \t\t            },\r\n");
      out.write("    \t\t        colModel :  [\r\n");
      out.write("    \t\t        \t            { label: '시즌코드',  key: true, name:'season_cd', index:'season_cd',  align:'left', hidden:true},\r\n");
      out.write("    \t\t        \t            { label: '시즌명',  name:'season_nm', index:'season_nm',  align:'left',   width:'10%'},\r\n");
      out.write("    \t\t        \t            { label: '시즌시작일',  name:'season_start_day', index:'season_start_day',  align:'left',   width:'10%'},\r\n");
      out.write("    \t\t        \t            { label: '시즌종료일',  name:'season_end_day', index:'season_end_day',  align:'left',   width:'10%'},\r\n");
      out.write("\t    \t\t \t                { label: '사용유무',  name:'use_yn', index:'use_yn', align:'left',   width:'10%' ,\r\n");
      out.write("\t    \t\t \t                \tformatter:jqGridFunc.useYn},\r\n");
      out.write("\t    \t\t \t                { label: '적용지점',  name:'season_centerinfo',  index:'season_centerinfo', align:'left',   width:'20%'},\r\n");
      out.write("\t    \t\t \t                { label: '설정',  name:'seasonSetting',  index:'seasonSetting', align:'left',   width:'10%', \r\n");
      out.write("\t    \t\t \t                \tformatter:jqGridFunc.seasonSetting },\r\n");
      out.write("\t    \t\t \t                { label: '수정자', name:'last_updusr_id',      index:'last_updusr_id',     align:'center', width:'14%'},\r\n");
      out.write("\t    \t\t\t                { label: '수정 일자', name:'last_updt_pnttm', index:'last_updt_pnttm', align:'center', width:'12%', \r\n");
      out.write("\t    \t\t\t                  sortable: 'date' ,formatter: \"date\", formatoptions: { newformat: \"Y-m-d\"}}\r\n");
      out.write("    \t\t\t                ],  //상단면 \r\n");
      out.write("    \t\t        rowNum : 10,  //레코드 수\r\n");
      out.write("    \t\t        rowList : [10,20,30,40,50,100],  // 페이징 수\r\n");
      out.write("    \t\t        pager: $('#pager'),  \r\n");
      out.write("    \t\t        pager : pager,\r\n");
      out.write("    \t\t        viewrecord : false,    // 하단 레코드 수 표기 유무\r\n");
      out.write("    \t\t        \r\n");
      out.write("    \t\t        refresh : true,\r\n");
      out.write("    \t            rownumbers : false, // 리스트 순번\r\n");
      out.write("    \t\t        loadonce : false,     // true 데이터 한번만 받아옴 \r\n");
      out.write("    \t\t        loadui : \"enable\",\r\n");
      out.write("    \t\t        loadtext:'데이터를 가져오는 중...',\r\n");
      out.write("    \t\t        emptyrecords : \"조회된 데이터가 없습니다\", //빈값일때 표시 \r\n");
      out.write("    \t\t        height : \"100%\",\r\n");
      out.write("    \t\t        autowidth:true,\r\n");
      out.write("    \t\t        shrinkToFit : true,\r\n");
      out.write("    \t\t        refresh : true,\r\n");
      out.write("    \t\t        multiselect:true, \r\n");
      out.write("    \t\t        loadComplete : function (data){\r\n");
      out.write("    \t\t        \t $(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);\r\n");
      out.write("    \t\t        \t var rowIds  = $(\"#listRepairLoaner\").jqGrid('getDataIDs');\r\n");
      out.write("    \t\t        \t    for( var n = 0; n <= rowIds.length; n++ ) {\r\n");
      out.write("    \t\t        \t        var rowId = rowIds[n];\r\n");
      out.write("    \t\t        \t        //cbox라는 class를 적용받는데 해당 class에서 선택을 방지\r\n");
      out.write("    \t\t        \t        $(\"#jqg_listRepairLoaner_\"+rowId).removeClass(\"cbox\");\r\n");
      out.write("    \t\t        \t    }\r\n");
      out.write("    \t\t        }, beforeSelectRow: function (rowid, e) {\r\n");
      out.write("    \t\t            var $myGrid = $(this);\r\n");
      out.write("    \t\t            var i = $.jgrid.getCellIndex($(e.target).closest('td')[0]);\r\n");
      out.write("    \t\t            var cm = $myGrid.jqGrid('getGridParam', 'colModel');\r\n");
      out.write("    \t\t            return (cm[i].name == 'cb'); // 선택된 컬럼이 cb가 아닌 경우 false를 리턴하여 체크선택을 방지\r\n");
      out.write("    \t\t        }, loadError:function(xhr, status, error) {\r\n");
      out.write("    \t\t            alert(\"loadError:\" + error); \r\n");
      out.write("    \t\t        },onSelectRow: function(rowId){\r\n");
      out.write("    \t                if(rowId != null) {  }// 체크 할떄\r\n");
      out.write("    \t            },ondblClickRow : function(rowid, iRow, iCol, e){\r\n");
      out.write("    \t            \tgrid.jqGrid('editRow', rowid, {keys: true});\r\n");
      out.write("    \t            },onCellSelect : function (rowid, index, contents, action){\r\n");
      out.write("    \t            \tvar cm = $(this).jqGrid('getGridParam', 'colModel');\r\n");
      out.write("    \t                //console.log(cm);\r\n");
      out.write("    \t                if (cm[index].name !='cb'){\r\n");
      out.write("    \t                \tjqGridFunc.fn_SeasonInfo(\"Edt\", $(this).jqGrid('getCell', rowid, 'season_cd'));\r\n");
      out.write("            \t\t    }\r\n");
      out.write("    \t            }\r\n");
      out.write("    \t\t    });\r\n");
      out.write("    \t\t}, useYn: function (cellvalue, options, rowObject){\r\n");
      out.write("                return rowObject.use_yn == \"Y\" ? \"사용\" : \"사용안함\";\r\n");
      out.write("            }, seasonSetting : function(cellvalue, options, rowObject){\r\n");
      out.write("            \treturn '<a href=\"javascript:jqGridFunc.fn_SeasonFloorInfo(&#39;'+rowObject.season_cd+'&#39;);\" class=\"orangeBtn\">층 관리</a>';\t\r\n");
      out.write("            } , refreshGrid : function(){\r\n");
      out.write("\t           $('#mainGrid').jqGrid().trigger(\"reloadGrid\");\r\n");
      out.write("\t        }, fn_search: function(){\r\n");
      out.write("\t    \t    $(\"#mainGrid\").setGridParam({\r\n");
      out.write("\t    \t    \t datatype\t: \"json\",\r\n");
      out.write("\t    \t    \t postData\t: JSON.stringify(  {\r\n");
      out.write("\t    \t    \t\t\"pageIndex\": $(\"#pager .ui-pg-input\").val(),\r\n");
      out.write("\t         \t\t\t\"searchCenter\" : $(\"#searchCenter\").val(),\r\n");
      out.write("\t         \t\t\t\"searchCondition\" : $(\"#searchCondition\").val(),\r\n");
      out.write("\t         \t\t\t\"searchKeyword\" : $(\"#searchKeyword\").val(),\r\n");
      out.write("\t         \t\t\t\"pageUnit\":$('.ui-pg-selbox option:selected').val()\r\n");
      out.write("\t         \t\t}),\r\n");
      out.write("\t    \t    \tloadComplete\t: function(data) {$(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);}\r\n");
      out.write("\t    \t     }).trigger(\"reloadGrid\");\r\n");
      out.write("\t        }, clearGrid : function() {\r\n");
      out.write("                $(\"#mainGrid\").clearGridData();\r\n");
      out.write("            }, fn_SeasonInfo : function (mode, seasonCd){\r\n");
      out.write("            \t$(\"#mode\").val(mode);\r\n");
      out.write("        \t    if (mode == \"Edt\"){\r\n");
      out.write("\t\t        \t$(\"#seasonCd\").val(seasonCd).prop('readonly', true);\r\n");
      out.write("\t\t        \t$(\"#btnUpdate\").text(\"수정\");\r\n");
      out.write("\t\t        \tvar params = {\"seasonCd\" : seasonCd};\r\n");
      out.write("\t\t        \tvar url = \"/backoffice/bld/seasonInfoDetail.do\";\r\n");
      out.write("\t\t        \tfn_Ajax(url, \"GET\", params, false, \r\n");
      out.write("\t\t\t          \t    function(result) {\r\n");
      out.write("\t     \t\t\t\t       if (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t\t \t\t\t\t    \t   common_popup(result.meesage, \"Y\", \"bas_menu_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   location.href=\"/backoffice/login.do\";\r\n");
      out.write("\t       \t\t\t\t\t   }else if (result.status == \"SUCCESS\"){\r\n");
      out.write("       \t\t\t\t\t\t       var obj  = result.regist;\r\n");
      out.write("       \t\t\t\t\t\t      \r\n");
      out.write("       \t\t\t\t\t\t       $(\"#seasonNm\").val(obj.season_nm);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#seasonStartDay\").val(obj.season_start_day);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#seasonEndDay\").val(obj.season_end_day);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#seasonDc\").val(obj.season_dc);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"input:radio[name='useYn']:radio[value='\"+obj.use_yn+\"']\").prop('checked', true)\r\n");
      out.write("       \t\t\t\t\t\t       fn_CheckboxChoice(\"seasonCenterinfo\", obj.season_centerinfo);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#btnSave\").text(\"수정\");\r\n");
      out.write("\t       \t\t\t\t\t   }else{\r\n");
      out.write("\t       \t\t\t\t\t\t   common_modelCloseM(result.message, \"bas_menu_add\");\r\n");
      out.write("\t       \t\t\t\t\t   }\r\n");
      out.write("\t\t\t     \t\t\t},\r\n");
      out.write("\t\t\t     \t\t\tfunction(request){\r\n");
      out.write("\t\t\t     \t\t\t    common_modelCloseM(\"ERROR : \" +request.status, \"bas_menu_add\");\r\n");
      out.write("\t\t\t     \t\t\t}\r\n");
      out.write("\t\t               );\r\n");
      out.write("\t\t        }else{\r\n");
      out.write("\t\t        \t$(\"#seasonCd\").val('').prop('readonly', false);\r\n");
      out.write("\t\t        \t$(\"#seasonNm\").val('');\r\n");
      out.write("\t\t\t\t    $(\"#seasonStartDay\").val('');\r\n");
      out.write("\t\t\t\t    $(\"#seasonEndDay\").val('');\r\n");
      out.write("\t\t\t\t    fn_CheckboxAllChange(\"seasonCenterinfo\", false);\r\n");
      out.write("\t\t\t\t    $(\"#seasonDc\").val('');\t\t\t\t  \r\n");
      out.write("\t\t        \t$(\"#btnUpdate\").text(\"입력\");\r\n");
      out.write("\t\t        \t$(\"#useAt_Y\").prop(\"checked\", true);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t        $(\"#bld_season_add\").bPopup();\r\n");
      out.write("           },fn_CheckForm  : function (){\r\n");
      out.write("        \t   if (any_empt_line_span(\"bld_season_add\", \"seasonNm\", \"시즌명를 입력해 주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("        \t   if (any_empt_line_span(\"bld_season_add\", \"seasonStartDay\", \"시즌 시작일를 선택해 주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("        \t   if (any_empt_line_span(\"bld_season_add\", \"seasonEndDay\", \"시즌 시작일를 선택해 주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("        \t   var choiceCenter = ckeckboxValue(\"시즌을 사용할 지점을 선택 하지 않았습니다.\", \"seasonCenterinfo\", \"bld_season_add\");\r\n");
      out.write("        \t \r\n");
      out.write("        \t   \r\n");
      out.write("\t\t\t   $(\"#seasonCenterinfo\").val(choiceCenter);\r\n");
      out.write("\t     \t   var commentTxt = ($(\"#mode\").val() == \"Ins\") ? \"신규 시즌 정보를 등록 하시겠습니까?\" : \"입력한 시즌 정보를 저장 하시겠습니까?\";\r\n");
      out.write("\t\t\t   $(\"#id_ConfirmInfo\").attr(\"href\", \"javascript:jqGridFunc.fn_update()\");\r\n");
      out.write("\t       \t   fn_ConfirmPop(commentTxt);\r\n");
      out.write("\t\t  }, fn_update : function(){\r\n");
      out.write("\t\t\t  $(\"#confirmPage\").bPopup().close();\r\n");
      out.write("\t\t\t  var url = \"/backoffice/bld/seasonInfoUpdate.do\";\r\n");
      out.write("\t\t      var params = {    'seasonCd' : $(\"#seasonCd\").val(),\r\n");
      out.write("\t\t\t\t    \t\t    'seasonNm' : $(\"#seasonNm\").val(),\r\n");
      out.write("\t\t\t\t    \t\t    'useYn' :fn_emptyReplace($(\"input[name='useYn']:checked\").val(),\"Y\"),\r\n");
      out.write("\t\t\t\t    \t\t    'seasonStartDay' : $(\"#seasonStartDay\").val(),\r\n");
      out.write("\t\t\t\t    \t\t    'seasonEndDay' : $(\"#seasonEndDay\").val(),\r\n");
      out.write("\t\t\t\t    \t\t    'seasonCenterinfo' : $(\"#seasonCenterinfo\").val(),\r\n");
      out.write("\t\t\t\t    \t\t    'seasonDc' : $(\"#seasonDc\").val(),\r\n");
      out.write("\t\t\t\t    \t\t    'mode' : $(\"#mode\").val()\r\n");
      out.write("\t\t    \t               }; \r\n");
      out.write("\t\t       fn_Ajax(url, \"POST\", params, false,\r\n");
      out.write("\t\t      \t\t\tfunction(result) {\r\n");
      out.write("\t\t    \t               if (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t\t \t\t\t\t    \t   common_popup(result.message, \"Y\",\"bld_season_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   location.href=\"/backoffice/login.do\";\r\n");
      out.write("\t\t   \t\t\t\t\t   }else if (result.status == \"OVERLAP FAIL\" ){\r\n");
      out.write("\t\t   \t\t\t\t\t\t    common_popup(result.message, \"N\", \"bld_season_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   jqGridFunc.fn_search();\r\n");
      out.write("\t\t   \t\t\t\t\t   }else if (result.status == \"SUCCESS\"){\r\n");
      out.write("\t\t   \t\t\t\t\t\t   //총 게시물 정리 하기'\r\n");
      out.write("\t\t   \t\t\t\t\t\t   common_modelClose(\"bld_season_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   jqGridFunc.fn_search();\r\n");
      out.write("\t\t   \t\t\t\t\t   }else if (result.status == \"FAIL\"){\r\n");
      out.write("\t\t   \t\t\t\t\t\t   common_popup(\"저장 도중 문제가 발생 하였습니다.\", \"Y\", \"bld_season_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   jqGridFunc.fn_search();\r\n");
      out.write("\t\t   \t\t\t\t\t   }\r\n");
      out.write("\t\t \t\t\t\t    },\r\n");
      out.write("\t\t \t\t\t\t    function(request){\r\n");
      out.write("\t\t \t\t\t\t\t    common_popup(\"Error:\" + request.status, \"Y\", \"bld_season_add\");\r\n");
      out.write("\t\t \t\t\t\t    }    \t\t\r\n");
      out.write("\t\t        );\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  }, fn_SeasonDel : function(){\r\n");
      out.write("\t\t\t  var menuArray = new Array();\r\n");
      out.write("\t\t\t  getEquipArray(\"mainGrid\", menuArray);\r\n");
      out.write("\t\t\t  if (menuArray.length > 0){\r\n");
      out.write("\t\t\t\t  $(\"#hid_DelCode\").val(menuArray.join(\",\"))\r\n");
      out.write("\t\t\t\t  $(\"#id_ConfirmInfo\").attr(\"href\", \"javascript:jqGridFunc.fn_del()\");\r\n");
      out.write("\t\t\t\t  menuArray = null;\r\n");
      out.write("       \t\t      fn_ConfirmPop(\"삭제 하시겠습니까?\");\r\n");
      out.write("\t\t\t  }else {\r\n");
      out.write("\t\t\t\t  menuArray = null;\r\n");
      out.write("\t\t\t\t  common_modelCloseM(\"체크된 값이 없습니다.\", \"savePage\");\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  }, fn_del : function (){\r\n");
      out.write("\t\t\t  var params = {'seasonCd': $(\"#hid_DelCode\").val() };\r\n");
      out.write("   \t\t      fn_uniDelAction(\"/backoffice/bld/seasonInfoDelete.do\",\"GET\", params, false, \"jqGridFunc.fn_search\");\r\n");
      out.write("\t\t  }, fn_SeasonFloorInfo : function (seasonCd){\r\n");
      out.write("\t\t\t  //시즌 정리 하기 \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  $(\"#dv_Title\").html(\"시즌 좌석 설정\");\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t  showLeft(); //좌측 메뉴 나오게 하기 \r\n");
      out.write("\t\t\t  var url = \"/backoffice/bld/seasonCenterLst.do\"\r\n");
      out.write("\t\t\t  var params = {\"seasonCd\": seasonCd};\r\n");
      out.write("\t\t\t  fn_Ajax(url, \"GET\", params, false,\r\n");
      out.write("\t\t      \t\t\tfunction(result) {\r\n");
      out.write("\t\t    \t               if (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t\t \t\t\t\t    \t   showLeft(); \r\n");
      out.write("\t\t   \t\t\t\t\t\t   location.href=\"/backoffice/login.do\";\r\n");
      out.write("\t\t   \t\t\t\t\t   }else if (result.status == \"SUCCESS\"){\r\n");
      out.write("\t\t   \t\t\t\t\t\t   //총 게시물 정리 하기'\r\n");
      out.write("\t\t   \t\t\t\t\t\t   //alert(result.status);\r\n");
      out.write("\t\t   \t\t\t\t\t\t  \r\n");
      out.write("\t\t   \t\t\t\t\t\t   \r\n");
      out.write("\t\t   \t\t\t\t\t\t   fn_comboListJson(\"searchCenterCd\", result.regist, \"fn_floorChange\", \"100px;\", \"\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   $(\"#searchCenterCd option:eq(0)\").prop(\"selected\", true);\r\n");
      out.write("\t\t   \t\t\t\t\t\t   fn_comboListJson(\"searchFloorCd\", result.floorlist, \"fn_partChange\", \"100px;\", \"\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   \r\n");
      out.write("\t\t   \t\t\t\t\t\t   $(\"#searchFloorCd option:eq(0)\").prop(\"selected\", true);\r\n");
      out.write("\t\t   \t\t\t\t\t\t   if ( result.partlist.length > 0){\r\n");
      out.write("\t\t   \t\t\t\t\t\t\t   $(\"#searchPartCd\").show();\r\n");
      out.write("\t\t   \t\t\t\t\t\t\t   fn_comboListJson(\"searchPartCd\", result.partlist, \"\", \"100px;\", \"\"); \r\n");
      out.write("\t\t   \t\t\t\t\t\t\t   $(\"#searchPartCd option:eq(0)\").prop(\"selected\", true);\r\n");
      out.write("\t\t   \t\t\t\t\t\t   }else {\r\n");
      out.write("\t\t   \t\t\t\t\t\t\t   $(\"#searchPartCd\").hide();\r\n");
      out.write("\t\t   \t\t\t\t\t\t   }\r\n");
      out.write("\t\t   \t\t\t\t\t\t   fn_GuiSearch();\r\n");
      out.write("\t\t   \t\t\t\t\t   }else if (result.status == \"FAIL\"){\r\n");
      out.write("\t\t   \t\t\t\t\t\t   showLeft(); \r\n");
      out.write("\t\t   \t\t\t\t\t\t   common_popup(result.message, \"N\", \"\");\r\n");
      out.write("\t\t   \t\t\t\t\t   }\r\n");
      out.write("\t\t \t\t\t\t    },\r\n");
      out.write("\t\t \t\t\t\t    function(request){\r\n");
      out.write("\t\t \t\t\t\t\t    common_popup(\"Error:\" + request.status, \"N\", \"\");\r\n");
      out.write("\t\t \t\t\t\t    }    \t\t\r\n");
      out.write("\t\t        );\r\n");
      out.write("\t\t  }, fn_SeasonGuiSearch: function () {\r\n");
      out.write("\t \t    \tif($(\"#searchFloorCd option\").length > 1 && $(\"#searchFloorCd\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\tif (any_empt_line_span_noPop(\"searchFloorCd\", \"층을 선택해주세요.\") == false) return;\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#searchPartCd option\").length > 1 && $(\"#searchPartCd\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\tif (any_empt_line_span_noPop(\"searchPartCd\", \"구역을 선택해주세요.\") == false) return;\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t \t    \tfn_GuiSearch();\r\n");
      out.write("\t\t \t}\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(386,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("regist");
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(386,0) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("regist");
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(386,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(386,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("/backoffice/bld/centerList.do");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<input type=\"hidden\" id=\"mode\" name=\"mode\">\r\n");
            out.write("<input type=\"hidden\" id=\"floorCd\" name=\"floorCd\">\r\n");
            out.write("<input type=\"hidden\" id=\"partExits\" name=\"partExits\">\r\n");
            out.write("<input type=\"hidden\" id=\"seasonCenterinfo\" name=\"seasonCenterinfo\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<div class=\"wrapper\">\r\n");
            out.write("  <!--// header -->\r\n");
            out.write("  ");
            if (_jspx_meth_c_005fimport_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("  <!-- header //-->\r\n");
            out.write("  <!--// contents-->\r\n");
            out.write("  <div id=\"contents\">\r\n");
            out.write("    <div class=\"breadcrumb\">\r\n");
            out.write("      <ol class=\"breadcrumb-item\">\r\n");
            out.write("        <li>시설 관리</li>\r\n");
            out.write("        <li class=\"active\">　> 시즌 관리</li>\r\n");
            out.write("      </ol>\r\n");
            out.write("    </div>\r\n");
            out.write("\r\n");
            out.write("    <h2 class=\"title\">시즌 관리</h2><div class=\"clear\"></div>\r\n");
            out.write("    <!--// dashboard -->\r\n");
            out.write("    <div class=\"dashboard\">\r\n");
            out.write("<!--contents-->\r\n");
            out.write("      <div class=\"boardlist\">\r\n");
            out.write("        <!--// search -->\r\n");
            out.write("        <div class=\"whiteBox searchBox\">\r\n");
            out.write("            <div class=\"sName\">\r\n");
            out.write("              <h3>검색 옵션</h3>\r\n");
            out.write("            </div>\r\n");
            out.write("          <div class=\"top\">\r\n");
            out.write("            <p>지점</p>\r\n");
            out.write("            <select id=\"searchCenter\" name=\"searchCenter\">\r\n");
            out.write("               <option value=\"\">지점</option>\r\n");
            out.write("               ");
            if (_jspx_meth_c_005fforEach_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("            </select>\r\n");
            out.write("            <p>검색어</p>\r\n");
            out.write("            <select id=\"searchCondition\"  name=\"searchCondition\">\r\n");
            out.write("              <option value=\"0\">선택</option>\r\n");
            out.write("              <option value=\"SEASON_NM\">시즌명</option>\r\n");
            out.write("              <option value=\"SEASON_DC\">시즌 상세 설명</option>\r\n");
            out.write("            </select>\r\n");
            out.write("            <input type=\"text\" id=\"searchKeyword\" name=\"searchKeyword\"  placeholder=\"검색어를 입력하세요.\">\r\n");
            out.write("          </div>\r\n");
            out.write("          <div class=\"inlineBtn\">\r\n");
            out.write("            <a href=\"javascript:jqGridFunc.fn_search()\"class=\"grayBtn\">검색</a>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"left_box mng_countInfo\">\r\n");
            out.write("          <p>총 : <span id=\"sp_totcnt\"></span>건</p>\r\n");
            out.write("          \r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"right_box\">\r\n");
            out.write("            <a href=\"javascript:jqGridFunc.fn_SeasonInfo('Ins', '')\" class=\"blueBtn\">시즌 등록</a>\r\n");
            out.write("            <a href=\"javascript:jqGridFunc.fn_SeasonDel()\"  class=\"grayBtn\">삭제</a>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"clear\"></div>\r\n");
            out.write("        <div class=\"whiteBox\">\r\n");
            out.write("          <table id=\"mainGrid\">\r\n");
            out.write("          </table>\r\n");
            out.write("\t\t  <div id=\"pager\" class=\"scroll\" style=\"text-align:center;\"></div>     \r\n");
            out.write("\t\t  <br/>\r\n");
            out.write("\t\t  <div id=\"paginate\"></div>\r\n");
            out.write("        </div>\r\n");
            out.write("                \r\n");
            out.write("      </div>\r\n");
            out.write("\r\n");
            out.write("    </div>\r\n");
            out.write("    \r\n");
            out.write("  </div>\r\n");
            out.write("  <!-- contents//-->\r\n");
            out.write("</div>\r\n");
            out.write("<!-- wrapper_end-->\r\n");
            out.write("<!-- // 시즌 관리 팝업 -->\r\n");
            out.write("<div data-popup=\"bld_season_add\" id=\"bld_season_add\" class=\"popup\">\r\n");
            out.write("  <div class=\"pop_con\">\r\n");
            out.write("      <a class=\"button b-close\">X</a>\r\n");
            out.write("      <h2 class=\"pop_tit\">시즌 정보</h2>\r\n");
            out.write("      <div class=\"pop_wrap\">\r\n");
            out.write("          <table class=\"detail_table\">\r\n");
            out.write("              <tbody>\r\n");
            out.write("                  <tr>\r\n");
            out.write("                    <th>시즌명</th>\r\n");
            out.write("                    <td><input type=\"text\" id=\"seasonNm\" name=\"seasonNm\">\r\n");
            out.write("                        <input type=\"hidden\" id=\"seasonCd\" name=\"seasonCd\">\r\n");
            out.write("                    </td>\r\n");
            out.write("                    <th>사용유무</th>\r\n");
            out.write("                    <td>\r\n");
            out.write("                      <label for=\"useAt_Y\"><input name=\"useYn\" type=\"radio\" id=\"useAt_Y\" value=\"Y\"/>사용</label>\r\n");
            out.write("                      <label for=\"useAt_N\"><input name=\"useYn\" type=\"radio\" id=\"useAt_N\" value=\"N\"/>사용 안함</label>\r\n");
            out.write("                    </td>\r\n");
            out.write("                  </tr>\r\n");
            out.write("                  <tr>\r\n");
            out.write("                    <th>시작일</th>\r\n");
            out.write("                    <td><input type=\"text\" id=\"seasonStartDay\" name=\"seasonStartDay\" class=\"cal_icon\"></td>\r\n");
            out.write("                    <th>종료일</th>\r\n");
            out.write("                    <td><input type=\"text\" id=\"seasonEndDay\" name=\"seasonEndDay\" class=\"cal_icon\"></td>\r\n");
            out.write("                  </tr>\r\n");
            out.write("                  <tr>\r\n");
            out.write("                    <th>해당 지점</th>\r\n");
            out.write("                    <td colspan=\"3\">\r\n");
            out.write("                      ");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                    </td>\r\n");
            out.write("                  </tr>\r\n");
            out.write("                  <tr>\r\n");
            out.write("                    <th>상세 설명</th>\r\n");
            out.write("                    <td colspan=\"3\">\r\n");
            out.write("                      <textarea style=\"width: 400px; height: 150px;\" id=\"seasonDc\" name=\"seasonDc\"></textarea>\r\n");
            out.write("                    </td>\r\n");
            out.write("                  </tr>\r\n");
            out.write("              </tbody>\r\n");
            out.write("          </table>\r\n");
            out.write("      </div>\r\n");
            out.write("      <div class=\"right_box\">\r\n");
            out.write("          <a href=\"javascript:common_modelClose('bld_season_add')\" class=\"grayBtn\">취소</a>\r\n");
            out.write("          <a href=\"javascript:jqGridFunc.fn_CheckForm()\" class=\"blueBtn\" id=\"btnUpdate\">저장</a>\r\n");
            out.write("      </div>\r\n");
            out.write("      <div class=\"clear\"></div>\r\n");
            out.write("  </div>\r\n");
            out.write("</div>\r\n");
            out.write("<!-- 시즌 관리 팝업 // -->\r\n");
            out.write("\r\n");
            out.write("<!--  GUI MODE -->\r\n");
            out.write("<!-- // 좌석 위치 세팅 팝업 -->\r\n");
            out.write("<!-- 좌석 GUI설정 팝업 -->\r\n");
            out.write("<nav class=\"cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right\" id=\"cbp-spmenu-s2\">\r\n");
            out.write("\t<a href=\"javascript:showLeft()\">닫기</a>\r\n");
            out.write("\t<!-- contents -->\r\n");
            out.write("\t<div class=\"content\">\r\n");
            out.write("\t\t<h2 class=\"title only_tit\"><span class=\"sp_title\"></span>위치 GUI Mode</h2>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t<div class=\"content back_map\">\r\n");
            out.write("\t\t<div class=\"box_shadow w1100 float_left\">\r\n");
            out.write("\t\t\t<div class=\"box_padding\">\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t<div class=\"page pinch-zoom-parent\">\r\n");
            out.write("\t\t\t\t\t<div class=\"pinch-zoom\" style=\"transform:unset !important;\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"map_box_sizing\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"mapArea floatL\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<ul id=\"seat_list\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t<div class=\"box_shadow w400 float_left left24\">\r\n");
            out.write("\t\t\t<div class=\"custom_bg\">\r\n");
            out.write("\t\t\t\t<div class=\"txt_con\">\r\n");
            out.write("\t\t\t\t\t<p>Business area</p>\r\n");
            out.write("\t\t\t\t\t<div class=\"btn_bot\">\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t<table class=\"search_tab\">\r\n");
            out.write("\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t    <th>지점</th>\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<select id=\"searchCenterCd\" name=\"searchCenterCd\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">검색 지점</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t</select>\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t<th>층</th>\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<select id=\"searchFloorCd\" name=\"searchFloorCd\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">검색 층수</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t</select>\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t   <th>구역</th>\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<select id=\"searchPartCd\" name=\"searchPartCd\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">검색 구역</option>\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t</select>\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
            out.write("\t\t\t\t\t\t\t    <a href=\"javascript:jqGridFunc.fn_SeasonGuiSearch()\" class=\"defaultBtn\">검색</a>\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t</tbody>\r\n");
            out.write("\t\t\t\t</table>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t<div class=\"box_padding\">\r\n");
            out.write("\t\t\t\t<div class=\"gui_text\">\r\n");
            out.write("\t\t\t\t\t<div class=\"txt_con\">\r\n");
            out.write("\t\t\t\t\t\t<p><span class=\"sp_title\"></span>위치</p>\r\n");
            out.write("\t\t\t\t\t\t<a href=\"javascript:fn_SeasonSave()\" class=\"defaultBtn\">저장</a>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<div class=\"scroll_table\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"scroll_div\">\r\n");
            out.write("\t\t\t\t\t\t\t<table class=\"total_tab gui_table\" id=\"seat_resultList\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"float: left;\">레이블</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"float: left;\">사용유무</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"float: left;\">금액</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"left: 14%; float: left;\">Top</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"right: 19.6%; float: right;\">Left</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
            out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
            out.write("\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t</div>\t\t\t\t        \r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("</nav>\r\n");
            out.write("\r\n");
            out.write("    <script type=\"text/javascript\">\r\n");
            out.write("\t \tvar menuRight = document.getElementById('cbp-spmenu-s2')\r\n");
            out.write("\t    function showLeft() {\r\n");
            out.write("\t \t    classie.toggle(menuRight, 'cbp-spmenu-open');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t \tfunction fn_layerClick(code, tr_code){\r\n");
            out.write("\t \t\tvar layerCss = rgb2hex($(\"#s\"+code).css(\"background-color\"));\r\n");
            out.write("\t \t\tvar color = (layerCss == \"#65a5d2\") ? \"#ffffff\" :\"#65a5d2\";\r\n");
            out.write("\t \t\t//tr 값 확인 \r\n");
            out.write("\t \t\t//tr_SEASON211109001C21110405_02_01_253\r\n");
            out.write("\t \t\talert(code);\r\n");
            out.write("\t \t\t$(\"#seat_resultList tr\").filter(\"#tr_\"+tr_code).css(\"background-color\", color);\r\n");
            out.write("\t \t\t$(\"#s\"+code).css(\"backgroundColor\", color);\r\n");
            out.write("\t \t\r\n");
            out.write("\t \t}\r\n");
            out.write("\t \tfunction fn_GuiSearch() {\t \t\t\r\n");
            out.write("\t\t\tvar title = \"시즌 좌석 관리\";\r\n");
            out.write("\t\t    $(\".sp_title\").text(title);\r\n");
            out.write("\t \t    var params = {\r\n");
            out.write("\t \t        \"searchCenter\": $(\"#searchCenterCd\").val(),\r\n");
            out.write("\t \t        \"searchFloorCd\": $(\"#searchFloorCd\").val(),\r\n");
            out.write("\t \t        \"searchPartCd\": fn_emptyReplace($(\"#searchPartCd\").val(), \"0\"),\r\n");
            out.write("\t \t        \"pageUnit\": \"2000\"\r\n");
            out.write("\t \t    };\r\n");
            out.write("\r\n");
            out.write("\t\t\tfn_Ajax\r\n");
            out.write("\t \t    (\r\n");
            out.write("\t\t\t\t\"/backoffice/bld/seasonSeatListAjax.do\",\r\n");
            out.write("\t\t\t\t\"POST\",\r\n");
            out.write("\t\t\t\tparams,\r\n");
            out.write("\t\t\t\tfalse,\r\n");
            out.write("\t \t        function(result) {\r\n");
            out.write("\t \t            if (result.status == \"LOGIN FAIL\") {\r\n");
            out.write("\t \t                showLeft(); \r\n");
            out.write("\t \t                location.href = \"/backoffice/login.do\";\r\n");
            out.write("\t \t            } else if (result.status == \"SUCCESS\") {\r\n");
            out.write("\t \t                //테이블 정리 하기\r\n");
            out.write("\t \t                var img = \"\";\r\n");
            out.write("\t \t                if (result.seatMapInfo != null) {\r\n");
            out.write("\t \t                    img = $(\"#partCd\").val() != \"0\" ? \"/upload/\"+result.seatMapInfo.part_map1 : \"/upload/\"+result.seatMapInfo.floor_map1;\r\n");
            out.write("\t \t                } \r\n");
            out.write("\t \t                console.log(\"img:\" + img)\r\n");
            out.write("\t \t                $('.mapArea').css({\r\n");
            out.write("\t                        \"background\": \"#fff url(\"+img+\")\",\r\n");
            out.write("\t                        'background-repeat': 'no-repeat',\r\n");
            out.write("\t                        'background-position': ' center'\r\n");
            out.write("\t                    });\r\n");
            out.write("\t \t               \r\n");
            out.write("\t \t                \r\n");
            out.write("\t\t\t\t\t\t$(\"#seat_resultList > tbody\").empty();\r\n");
            out.write("\t \t                if (result.resultlist.length > 0) {\r\n");
            out.write("\t \t                    var shtml = '';\r\n");
            out.write("\t \t                    var thtml = '';\r\n");
            out.write("\t \t                    var obj = result.resultlist;\r\n");
            out.write("\t \t                    \r\n");
            out.write("\t \t                    \r\n");
            out.write("\t \t                    \r\n");
            out.write(" \t                        for (var i in result.resultlist) {\r\n");
            out.write(" \t                        \tvar check = (obj[i].use_yn == \"Y\") ? \"checked\" : \"\";\r\n");
            out.write(" \t                        \tif (check == \"checked\"){\r\n");
            out.write(" \t                        \t\tshtml += '<li id=\"s' + trim(obj[i].season_seat_label) + '\" class=\"seat\" season_seat-cd=\"' + obj[i].season_seat_cd + '\" name=\"' + obj[i].season_seat_cd + '\" onClick=\"fn_layerClick(&#34;' + trim(obj[i].season_seat_label ) + '&#34;,&#34;' + trim(obj[i].season_seat_cd ) + '&#34;)\">' + fn_NVL(obj[i].season_seat_order) + '</li>';\r\n");
            out.write(" \t                        \t\t$('#seat_list').html(shtml);\r\n");
            out.write(" \t                        \t\t//동적 클릭 하는 부분 처리 나중에 확인 하기 \r\n");
            out.write(" \t                        \t\t\r\n");
            out.write(" \t                        \t}\r\n");
            out.write(" \t                        \tthtml += \"<tr id='tr_\"+obj[i].season_seat_cd+\"'>\" +\r\n");
            out.write("                                \"   <td><input type='text' id='label_\"+obj[i].season_seat_cd+\"' value='\"+ obj[i].season_seat_label +\"' style='width:80px;' />\"+\r\n");
            out.write("                                \"   <input type='hidden' name='season_seat_cd' value='\" + obj[i].season_seat_cd + \"'></td>\" +\r\n");
            out.write("                                \"   <td><input type='checkbox' id='check_\"+obj[i].season_seat_cd+\"' \"+check+\">\" +\r\n");
            out.write("                                \"   <td><input type='text' id='cost_\"+obj[i].season_seat_cd+\"' value='\"+ obj[i].season_cost +\"'  style='width:80px;'/></td>\"+\r\n");
            out.write("                                \"   <td><a href='javascript:top_up(&#34;\" + obj[i].season_seat_cd + \"&#34;)' class='up'></a>\" +\r\n");
            out.write("                                \"   <input type='text' id='top_\" + obj[i].season_seat_cd + \"' name='top_\" + obj[i].season_seat_cd + \"' value='\" + obj[i].season_seat_top + \"' onchange='top_chage(&#34;\" + obj[i].season_seat_cd + \"&#34;, this.value)'  style='width:70px;'>\" +\r\n");
            out.write("                                \"   <a href='javascript:top_down(&#34;\" + obj[i].season_seat_cd + \"&#34;)' class='down'></a></td>\" +\r\n");
            out.write("                                \"   <td><a href='javascript:left_up(&#34;\" + obj[i].season_seat_cd + \"&#34;)' class='leftB'></a>\" +\r\n");
            out.write("                                \"   <input type='text' id='left_\" + obj[i].season_seat_cd + \"' name='left_\" + obj[i].season_seat_cd + \"' value='\" + obj[i].season_seat_left + \"' onchange='left_chage(&#34;\" + obj[i].season_seat_cd + \"&#34, this.value)'  style='width:70px;'>\" +\r\n");
            out.write("                                \"   <a href='javascript:left_down(&#34;\" + obj[i].season_seat_cd + \"&#34;)' class='rightB'></a></td>\" +\r\n");
            out.write("                                \"</tr>\";\r\n");
            out.write("                                $(\"#seat_resultList > tbody\").append(thtml);\r\n");
            out.write("                                thtml = \"\";\r\n");
            out.write(" \t                        \t\r\n");
            out.write(" \t                        }\r\n");
            out.write("\t \t                    //여기 부분 확인 하기\r\n");
            out.write(" \t                        for (var i in result.resultlist) {\r\n");
            out.write(" \t                        \tif (obj[i].use_yn == \"Y\"){\r\n");
            out.write(" \t                        \t\t$('.mapArea ul li#s' + trim(obj[i].season_seat_label)).css({\r\n");
            out.write("\t \t                                \"top\": obj[i].season_seat_top + \"px\",\r\n");
            out.write("\t \t                                \"left\": obj[i].season_seat_left + \"px\"\r\n");
            out.write("\t \t                            });  \r\n");
            out.write(" \t                        \t}\r\n");
            out.write(" \t                        }\r\n");
            out.write("\t \t                    $('.seat').dragmove();\r\n");
            out.write("\t \t                } else {\r\n");
            out.write("\t \t                    $('#seat_list').html('');\r\n");
            out.write("\t \t                    \"\"\r\n");
            out.write("\t \t                }\r\n");
            out.write("\t \t            } else {\r\n");
            out.write("\t \t                showLeft(); \r\n");
            out.write("\t\t\t\t\t    common_popup(result.message, \"N\", \"\");\r\n");
            out.write("\t \t            }\r\n");
            out.write("\t \t        },\r\n");
            out.write("\t \t        function(request) {\r\n");
            out.write("\t \t            showLeft(); \r\n");
            out.write("\t\t\t\t    common_popup(\"ERROR : \" + request.status, \"N\", \"\");\r\n");
            out.write("\t \t        }\r\n");
            out.write("\t \t    );\r\n");
            out.write("\t \t}\r\n");
            out.write("\t\r\n");
            out.write("\r\n");
            out.write("\t \t\r\n");
            out.write("\t \t\r\n");
            out.write("\t \t\r\n");
            out.write("\t \tfunction fn_floorChange() {\r\n");
            out.write("\t \t\t\r\n");
            out.write("\t \t\tvar url = \"/backoffice/bld/floorComboInfo.do\"\r\n");
            out.write("\t \t\tvar params = {\"centerCd\" : $(\"#searchCenterCd\").val()}\r\n");
            out.write("\t \t\tvar returnVal = uniAjaxReturn(url, \"GET\", false, params, \"lst\");\r\n");
            out.write("\t \t\tfn_comboListJson(\"searchFloorCd\", returnVal, \"fn_partChange\", \"100px;\", \"\");\r\n");
            out.write("\t \t\tif (returnVal.length > 0){\r\n");
            out.write("\t \t\t\t$(\"#searchFloorCd option:eq(0)\").prop(\"selected\", true);\r\n");
            out.write("\t \t\t}else {\r\n");
            out.write("\t \t\t\t$(\"#searchFloorCd\").hide();\r\n");
            out.write("\t \t\t}\r\n");
            out.write("\t \t\t$(\"#searchPartCd\").hide();\r\n");
            out.write("\t\t}\r\n");
            out.write("\t\tfunction fn_partChange(){\r\n");
            out.write("\t\t\tvar url = \"/backoffice/bld/partInfoComboList.do\"\r\n");
            out.write("\t\t    var params = {\"floorCd\" : $(\"#searchFloorCd\").val()}\r\n");
            out.write("\t\t \tvar returnVal = uniAjaxReturn(url, \"GET\", false, params, \"lst\");\r\n");
            out.write("\t\t\tfn_comboListJson(\"searchPartCd\", returnVal, \"\", \"100px;\", \"\");\r\n");
            out.write("\t\t\tif (returnVal.length > 0){\r\n");
            out.write("\t \t\t\t$(\"#searchPartCd option:eq(0)\").prop(\"selected\", true);\r\n");
            out.write("\t \t\t\t$(\"#searchPartCd\").show();\r\n");
            out.write("\t \t\t}else {\r\n");
            out.write("\t \t\t\t\r\n");
            out.write("\t \t\t\t$(\"#searchPartCd\").hide();\r\n");
            out.write("\t \t\t\t//검색으로 바로 가기 \r\n");
            out.write("\t \t\t\tfn_GuiSearch();\r\n");
            out.write("\t \t\t}\r\n");
            out.write("\t\t}\r\n");
            out.write("\t\r\n");
            out.write("\t \tfunction fn_SeasonSave() {\r\n");
            out.write("\t    \t$(\"#id_ConfirmInfo\").attr(\"href\", \"javascript:fn_SeasonUpdate()\");\r\n");
            out.write("       \t\tfn_ConfirmPop('저장 하시겠습니까?');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t \tfunction fn_SeasonUpdate(){\r\n");
            out.write("\t \t\t$(\"#confirmPage\").bPopup().close();\r\n");
            out.write("\t \t\t\r\n");
            out.write("\t \t\t\r\n");
            out.write(" \t        var SeasonSeatArray = new Array();\r\n");
            out.write(" \t        //여기 부분 좌표값으로 가지고 오기 \r\n");
            out.write(" \t        $(\"input:hidden[name=season_seat_cd]\").each(function() {\r\n");
            out.write(" \t            var SeasonSeatInfo = new Object();\r\n");
            out.write(" \t            SeasonSeatInfo.seasonSeatCd = $(this).val();\r\n");
            out.write(" \t            SeasonSeatInfo.seasonSeatLabel = $(\"#label_\" + SeasonSeatInfo.seasonSeatCd).val();\r\n");
            out.write(" \t            SeasonSeatInfo.seasonCost = $(\"#cost_\" + SeasonSeatInfo.seasonSeatCd).val();\r\n");
            out.write(" \t            SeasonSeatInfo.useYn =  $(\"#check_\" + SeasonSeatInfo.seasonSeatCd).is(\":checked\") == true ? \"Y\" : \"N\";\r\n");
            out.write(" \t            SeasonSeatInfo.seasonSeatTop = $(\"#top_\" + SeasonSeatInfo.seasonSeatCd).val(); // $(this).css('top').replace('px', '');\r\n");
            out.write(" \t            SeasonSeatInfo.seasonSeatLeft = $(\"#left_\" + SeasonSeatInfo.seasonSeatCd).val(); //$(this).css('left').replace('px', '');\r\n");
            out.write(" \t            SeasonSeatArray.push(SeasonSeatInfo);\r\n");
            out.write(" \t        });\r\n");
            out.write("\r\n");
            out.write(" \t        var param = new Object();\r\n");
            out.write(" \t        param.data = SeasonSeatArray;\r\n");
            out.write(" \t        if (SeasonSeatArray.length == 0) {\r\n");
            out.write(" \t            common_popup('저장할 내용이 없습니다.', \"N\", \"\");\r\n");
            out.write(" \t            return false;\r\n");
            out.write(" \t        }\r\n");
            out.write(" \t        var url = \"/backoffice/bld/seasonGuiUpdate.do\";\r\n");
            out.write(" \t        fn_Ajax(url, \"POST\", param, false,\r\n");
            out.write(" \t            function(result) {\r\n");
            out.write(" \t                if (result.status == \"LOGIN FAIL\") {\r\n");
            out.write(" \t                \t//추후 로그인 부분 확인 하기 \r\n");
            out.write(" \t                \tlocation.href = \"/backoffice/login.do\";\r\n");
            out.write(" \t                } else if (result.status == \"SUCCESS\") {\r\n");
            out.write(" \t                    common_popup('수정되었습니다.', \"Y\", \"\");\r\n");
            out.write(" \t                    fn_GuiSearch();\r\n");
            out.write(" \t                }else {\r\n");
            out.write(" \t                \tcommon_popup(result.message, \"N\", \"\");\r\n");
            out.write(" \t                } \r\n");
            out.write(" \t            },\r\n");
            out.write(" \t            function(request) {\r\n");
            out.write(" \t            \tcommon_popup(\"ERROR : \" + request.status, \"N\", \"\");\r\n");
            out.write(" \t            }\r\n");
            out.write(" \t        );\r\n");
            out.write("\t    }\r\n");
            out.write("\t\r\n");
            out.write("\t \t/***********************************\r\n");
            out.write("\t \t * + - 버튼\r\n");
            out.write("\t \t ************************************/\r\n");
            out.write("\t \tfunction top_up(str) {\r\n");
            out.write("\t \t    var top = parseInt($('#top_' + str).val()) + 1;\r\n");
            out.write("\t \t    $('#top_' + str).val(top);\r\n");
            out.write("\t \t    $('li[name=\"' + str + '\"]').css('top', top + 'px');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t\r\n");
            out.write("\t \tfunction top_down(str) {\r\n");
            out.write("\t \t    var top = parseInt($('#top_' + str).val()) - 1;\r\n");
            out.write("\t \t    $('#top_' + str).val(top);\r\n");
            out.write("\t \t    $('li[name=\"' + str + '\"]').css('top', top + 'px');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t\r\n");
            out.write("\t \tfunction left_up(str) {\r\n");
            out.write("\t \t    var left = parseInt($('#left_' + str).val()) + 1;\r\n");
            out.write("\t \t    $('#left_' + str).val(left);\r\n");
            out.write("\t \t    $('li[name=\"' + str + '\"]').css('left', left + 'px');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t\r\n");
            out.write("\t \tfunction left_down(str) {\r\n");
            out.write("\t \t    var left = parseInt($('#left_' + str).val()) - 1;\r\n");
            out.write("\t \t    $('#left_' + str).val(left);\r\n");
            out.write("\t \t    $('li[name=\"' + str + '\"]').css('left', left + 'px');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t\r\n");
            out.write("\t\r\n");
            out.write("\t \t/***********************************\r\n");
            out.write("\t \t * text mode top 수정\r\n");
            out.write("\t \t ************************************/\r\n");
            out.write("\t \tfunction top_chage(str, str2) {\r\n");
            out.write("\t \t    console.log('str : ' + str + ', str2 : ' + str2);\r\n");
            out.write("\t \t    $('li[name=\"' + str + '\"]').css('top', str2 + 'px');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t\r\n");
            out.write("\t \t/***********************************\r\n");
            out.write("\t \t * text mode left 수정\r\n");
            out.write("\t \t ************************************/\r\n");
            out.write("\t \tfunction left_chage(str, str2) {\r\n");
            out.write("\t \t    $('li[name=\"' + str + '\"]').css('left', str2 + 'px');\r\n");
            out.write("\t \t}\r\n");
            out.write("\t</script>\r\n");
            out.write("    ");
            if (_jspx_meth_c_005fimport_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("    <script type=\"text/javascript\" src=\"/resources/js/back_common.js\"></script>\r\n");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(395,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/backoffice/inc/top_inc.do");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(420,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/backoffice/bld/seasonList.jsp(420,15) '${centerCombo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${centerCombo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(420,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("centerCombo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                     <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerCombo.center_cd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerCombo.center_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t   ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(489,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/backoffice/bld/seasonList.jsp(489,22) '${centerCombo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${centerCombo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(489,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("centerCombo");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                         <input type=\"checkbox\" name=\"seasonCenterinfo\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerCombo.center_cd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerCombo.center_cd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" />\r\n");
            out.write("                         ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerCombo.center_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("\t\t\t          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bld/seasonList.jsp(838,4) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/backoffice/inc/popup_common.do");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
