/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-11-30 08:38:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backoffice.rsv;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blackList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no;\" />\r\n");
      out.write("    <title>경륜경정 스마트입장 관리자</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/reset.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/paragraph.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\" />\r\n");
      out.write("    <script src=\"/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/bpopup.js\"></script>\r\n");
      out.write("    <!-- datepicker-->\r\n");
      out.write("    <script src=\"/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("    <!-- 체크 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- jqGrid -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/jqgrid/src/css/ui.jqgrid.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/src/i18n/grid.locale-kr.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery.browser = {};\r\n");
      out.write("\t\t(function () {\r\n");
      out.write("\t\t    jQuery.browser.msie = false;\r\n");
      out.write("\t\t    jQuery.browser.version = 0;\r\n");
      out.write("\t\t    if (navigator.userAgent.match(/MSIE ([0-9]+)\\./)) {\r\n");
      out.write("\t\t        jQuery.browser.msie = true;\r\n");
      out.write("\t\t        jQuery.browser.version = RegExp.$1;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t})();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t    .ui-jqgrid .ui-jqgrid-htable th div{\r\n");
      out.write("\t\t\toutline-style: none;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t    .ui-jqgrid tr.jqgrow {\r\n");
      out.write("\t\t\toutline-style: none;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("    </style>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/backoffice/rsv/blackList.jsp(59,1) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("regist");
      // /WEB-INF/jsp/backoffice/rsv/blackList.jsp(59,1) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("regist");
      // /WEB-INF/jsp/backoffice/rsv/blackList.jsp(59,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/jsp/backoffice/rsv/blackList.jsp(59,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("/backoffice/rsv/blackList.do");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t<input type=\"hidden\" id=\"mode\" name=\"mode\">\r\n");
            out.write("\t<input type=\"hidden\" id=\"blklstSeq\" name=\"blklstSeq\">\r\n");
            out.write("\t<input type=\"hidden\" id=\"searchBlklstDvsn\" name=\"searchBlklstDvsn\" value=\"BLKLST_DVSN_1\">\r\n");
            out.write("\t\r\n");
            out.write("\t<div class=\"wrapper\">\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fimport_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("  \t\t<!--// contents-->\r\n");
            out.write("  \t\t<div id=\"contents\">\r\n");
            out.write("    \t\t<div class=\"breadcrumb\">\r\n");
            out.write("      \t\t\t<ol class=\"breadcrumb-item\">\r\n");
            out.write("        \t\t\t<li>고객 관리</li>\r\n");
            out.write("        \t\t\t<li class=\"active\">　> 출입통제 관리</li>\r\n");
            out.write("      \t\t\t</ol>\r\n");
            out.write("    \t\t</div>\r\n");
            out.write("\r\n");
            out.write("\t\t    <h2 class=\"title\">출입통제 관리</h2><div class=\"clear\"></div>\r\n");
            out.write("\t\t    <!--// dashboard -->\r\n");
            out.write("\t\t    <div class=\"dashboard\">\r\n");
            out.write("\t\t\t\t<!--contents-->\r\n");
            out.write("\t\t      \t<div class=\"boardlist\">\r\n");
            out.write("\t\t        \t<div class=\"whiteBox searchBox\">\r\n");
            out.write("\t\t            \t<div class=\"sName\">\r\n");
            out.write("\t\t                \t<h3>검색 옵션</h3>\r\n");
            out.write("\t\t              \t</div>\r\n");
            out.write("\t\t          \t\t<div class=\"top\">\r\n");
            out.write("\t\t            \t\t<p>검색 구분</p>\r\n");
            out.write("\t\t            \t\t<select id=\"searchCondition\">\r\n");
            out.write("\t\t              \t\t\t<option value=\"0\">아이디</option>\r\n");
            out.write("\t\t              \t\t\t<option value=\"\">이름</option>\r\n");
            out.write("\t\t              \t\t\t<option value=\"\">전화번호</option>\r\n");
            out.write("\t\t            \t\t</select>\r\n");
            out.write("\t\t            \t\t<input type=\"text\" id=\"searchKeyword\" placeholder=\"검색어를 입력하세요.\">\r\n");
            out.write("\t\t          \t\t</div>\r\n");
            out.write("\t\t          \t\t<div class=\"inlineBtn\">\r\n");
            out.write("\t\t            \t\t<a href=\"javascript:jqGridFunc.fn_search();\"class=\"grayBtn\">검색</a>\r\n");
            out.write("\t\t          \t\t</div>\r\n");
            out.write("\t\t        \t</div>\r\n");
            out.write("\t\t        \t\r\n");
            out.write("\t\t        \t<div class=\"left_box mng_countInfo\">\r\n");
            out.write("\t\t          \t\t<p>총 : <span id=\"sp_totcnt\">100</span>건</p>\r\n");
            out.write("\t\t        \t</div>\t\r\n");
            out.write("\t\t        \t<div class=\"clear\"></div>\r\n");
            out.write("\t\t        \t\r\n");
            out.write("\t\t        \t<div class=\"tabs blacklist\">\r\n");
            out.write("\t\t          \t\t<div id=\"BLKLST_DVSN_1\" class=\"tab active\" onclick=\"blackUserService.fn_changeBlklstDvsn(this);\">블랙리스트</div>\r\n");
            out.write("\t\t          \t\t<div id=\"BLKLST_DVSN_2\" class=\"tab\" onclick=\"blackUserService.fn_changeBlklstDvsn(this);\">자가출입통제</div>\r\n");
            out.write("\t\t          \t\t<div id=\"BLKLST_DVSN_3\" class=\"tab\" onclick=\"blackUserService.fn_changeBlklstDvsn(this);\">패널티 고객</div>\r\n");
            out.write("\t\t        \t</div>\r\n");
            out.write("\t\t        \t\r\n");
            out.write("\t\t        \t<div class=\"right_box\">\r\n");
            out.write("\t\t            \t<a data-popup-open=\"blacklist_add\" class=\"blueBtn\">입장 제한 고객 등록</a>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
            out.write("\t\t        \t\r\n");
            out.write("\t\t\t\t\t<div class=\"whiteBox\">\r\n");
            out.write("\t\t\t\t\t\t<table id=\"mainGrid\">\r\n");
            out.write("\t\t\t\t        \t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t<div id=\"pager\" class=\"scroll\" style=\"text-align:center;\"></div>     \r\n");
            out.write("\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<div id=\"paginate\"></div>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t    \t</div>\r\n");
            out.write("\t\t  \t</div>\r\n");
            out.write("  \t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- wrapper_end-->\r\n");
            out.write("\t<!-- // 입장제한고객 등록 팝업 -->\r\n");
            out.write("\t<div id=\"blacklist_add\" data-popup=\"blacklist_add\" class=\"popup\">\r\n");
            out.write("\t  <div class=\"pop_con\">\r\n");
            out.write("\t      <a class=\"button b-close\">X</a>\r\n");
            out.write("\t      <h2 class=\"pop_tit\">입장 제한 고객 등록</h2>\r\n");
            out.write("\t      <div class=\"pop_wrap\">\r\n");
            out.write("\t          <table class=\"detail_table blacklist_add_table\">\r\n");
            out.write("\t              <tbody>\r\n");
            out.write("\t                  <tr>\r\n");
            out.write("\t                    <th>회원 조회</th>\r\n");
            out.write("\t                    <td>\r\n");
            out.write("\t                      <select id=\"userSearchCondition\">\r\n");
            out.write("\t                          <option value=\"user_id\">아이디</option>\r\n");
            out.write("\t                          <option value=\"user_nm\">이름</option>    \r\n");
            out.write("\t                          <option value=\"user_phone\">전화번호</option>             \r\n");
            out.write("\t                      </select>\r\n");
            out.write("\t                      <input type=\"text\" id=\"userSearchKeyword\">\r\n");
            out.write("\t                      <a href=\"javascript:blackUserService.fn_searchResult('user');\" class=\"blueBtn\">조회</a>\r\n");
            out.write("\t                    </td>\r\n");
            out.write("\t                      <th>아이디 </th>\r\n");
            out.write("\t                      <td><input type=\"text\" id=\"userId\" readonly></td>\r\n");
            out.write("\t                  </tr>\r\n");
            out.write("\t                  <tr>\r\n");
            out.write("\t                      <th>이름 </th>\r\n");
            out.write("\t                      <td><input type=\"text\" id=\"userNm\" readonly></td>\r\n");
            out.write("\t                      <th>전화번호 </th>\r\n");
            out.write("\t                      <td><input type=\"text\" id=\"userPhone\" readonly></td>\r\n");
            out.write("\t                  </tr>\r\n");
            out.write("\t                  <tr>\r\n");
            out.write("\t                    <th>제한 유형</th>\r\n");
            out.write("\t                    <td>\r\n");
            out.write("\t                        <select id=\"blklstDvsn\">\r\n");
            out.write("\t                          <option value=\"BLKLST_DVSN_1\">블랙리스트</option>\r\n");
            out.write("\t                          <option value=\"BLKLST_DVSN_2\">자가출입통제</option>\r\n");
            out.write("\t                          <option value=\"BLKLST_DVSN_3\">패널티 고객</option>\r\n");
            out.write("\t                        </select>\r\n");
            out.write("\t                    </td>\r\n");
            out.write("\t<!--                     <th>회원 구분</th>\r\n");
            out.write("\t                    <td><input type=\"text\" id=\"\"></td> -->\r\n");
            out.write("\t                  </tr>\r\n");
            out.write("\t                  <tr>\r\n");
            out.write("\t                    <th>상세 내역</th>\r\n");
            out.write("\t                      <td colspan=\"3\">\r\n");
            out.write("\t                        <input type=\"text\" id=\"fulltxt\">\r\n");
            out.write("\t                      </td>\r\n");
            out.write("\t                  </tr>\r\n");
            out.write("\t              </tbody>\r\n");
            out.write("\t          </table>\r\n");
            out.write("\t      </div>\r\n");
            out.write("\t      <div class=\"right_box\">\r\n");
            out.write("\t          <a href=\"\" class=\"grayBtn\">취소</a>\r\n");
            out.write("\t          <a href=\"\" class=\"blueBtn\">저장</a>\r\n");
            out.write("\t      </div>\r\n");
            out.write("\t      <div class=\"clear\"></div>\r\n");
            out.write("\t  </div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- 관리자 등록 팝업 // -->\r\n");
            out.write("\t<!-- // 관리자 검색 팝업 -->\r\n");
            out.write("\t<div id=\"search_result\" class=\"popup\">\r\n");
            out.write("\t\t<div class=\"pop_con\">\r\n");
            out.write("\t\t\t<h2 class=\"pop_tit\">검색 결과</h2>\r\n");
            out.write("\t      \t<div id=\"searchResult\" class=\"pop_wrap\">\r\n");
            out.write("\t        \t<table id=\"searchResultTable\" class=\"whiteBox main_table\">\r\n");
            out.write("\t        \t\r\n");
            out.write("\t        \t</table>\r\n");
            out.write("\t      \t</div>\r\n");
            out.write("\t  \t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t<!-- 관리자 검색 팝업 // -->\r\n");
            out.write("\r\n");
            out.write("<script type=\"text/javascript\">\r\n");
            out.write("\t$(document).ready(function() { \r\n");
            out.write("\t\tjqGridFunc.setGrid(\"mainGrid\");\r\n");
            out.write("\t});\r\n");
            out.write("    \r\n");
            out.write("\tvar jqGridFunc = {\r\n");
            out.write("\t\tsetGrid : function(gridOption) {\r\n");
            out.write("\t\t\tvar grid = $('#'+gridOption);\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t//ajax 관련 내용 정리 하기 \r\n");
            out.write("\t\t\tvar postData = {\"pageIndex\": \"1\", \"searchBlklstDvsn\" : $(\"#searchBlklstDvsn\").val()};\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tgrid.jqGrid({\r\n");
            out.write("\t\t\t\turl : '/backoffice/rsv/blackListAjax.do',\r\n");
            out.write("\t\t\t\tmtype : 'POST',\r\n");
            out.write("\t\t\t\tdatatype : 'json',\r\n");
            out.write("\t\t\t\tpager: $('#pager'),  \r\n");
            out.write("\t\t\t\tajaxGridOptions: { contentType: \"application/json; charset=UTF-8\" },\r\n");
            out.write("\t\t\t\tajaxRowOptions: { contentType: \"application/json; charset=UTF-8\", async: true },\r\n");
            out.write("\t\t\t\tajaxSelectOptions: { contentType: \"application/json; charset=UTF-8\", dataType: \"JSON\" }, \r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\tpostData : JSON.stringify(postData),\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\tjsonReader : {\r\n");
            out.write("\t\t\t\t\troot : 'resultlist',\r\n");
            out.write("\t\t\t\t\t\"page\":\"paginationInfo.currentPageNo\",\r\n");
            out.write("\t\t\t\t\t\"total\":\"paginationInfo.totalPageCount\",\r\n");
            out.write("\t\t\t\t\t\"records\":\"paginationInfo.totalRecordCount\",\r\n");
            out.write("\t\t\t\t\trepeatitems:false\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\t//상단면\r\n");
            out.write("\t\t\t\tcolModel :  \r\n");
            out.write("\t\t\t\t[\r\n");
            out.write("\t\t\t\t\t{label: 'blklst_seq', key: true, name:'blklst_seq', index:'blklst_seq', align:'center', hidden:true},\r\n");
            out.write("\t\t\t\t\t{label: '아이디', name:'user_id', index:'user_id', align:'center'},\r\n");
            out.write("\t\t\t\t\t{label: '전화번호', name:'user_phone', index:'user_phone', align:'center'},\r\n");
            out.write("\t\t\t\t\t{label: '유형', name:'blklst_dvsn', index:'blklst_dvsn', align:'center'},\r\n");
            out.write("\t\t\t\t\t{label: '상세내용', name:'blklst_reason', index:'blklst_reason', align:'center'},\r\n");
            out.write("\t\t\t\t\t{label: '해제', name:'resv_qr_print', index:'resv_qr_print', align:'center', sortable : false, formatter:jqGridFunc.buttonSetting},\r\n");
            out.write("\t\t\t\t], \r\n");
            out.write("\t\t\t\trowNum : 10,  //레코드 수\r\n");
            out.write("\t\t\t\trowList : [10,20,30,40,50,100],  // 페이징 수\r\n");
            out.write("\t\t\t\tpager : pager,\r\n");
            out.write("\t\t\t\trefresh : true,\r\n");
            out.write("\t\t\t    multiselect : false, // 좌측 체크박스 생성\r\n");
            out.write("\t\t\t\trownumbers : false, // 리스트 순번\r\n");
            out.write("\t\t\t\tviewrecord : true,  // 하단 레코드 수 표기 유무\r\n");
            out.write("\t\t\t\t//loadonce : false, // true 데이터 한번만 받아옴 \r\n");
            out.write("\t\t\t\tloadui : \"enable\",\r\n");
            out.write("\t\t\t\tloadtext:'데이터를 가져오는 중...',\r\n");
            out.write("\t\t\t\temptyrecords : \"조회된 데이터가 없습니다\", //빈값일때 표시 \r\n");
            out.write("\t\t\t\theight : \"100%\",\r\n");
            out.write("\t\t\t\tautowidth:true,\r\n");
            out.write("\t\t\t\tshrinkToFit : true,\r\n");
            out.write("\t\t\t\trefresh : true,\r\n");
            out.write("\t\t\t\tloadComplete : function (data) {\r\n");
            out.write("\t\t\t\t\t$(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\tloadError:function(xhr, status, error) {\r\n");
            out.write("\t\t\t\t\talert(error); \r\n");
            out.write("\t\t\t\t}, \r\n");
            out.write("\t\t\t\tonPaging: function(pgButton) {\r\n");
            out.write("\t\t\t\t\tvar gridPage = grid.getGridParam('page'); //get current  page\r\n");
            out.write("\t\t\t\t\tvar lastPage = grid.getGridParam(\"lastpage\"); //get last page \r\n");
            out.write("\t\t\t\t\tvar totalPage = grid.getGridParam(\"total\");\r\n");
            out.write("    \t\t              \r\n");
            out.write("\t\t\t\t\tif (pgButton == \"next\"){\r\n");
            out.write("\t\t\t\t\t\tif (gridPage < lastPage ){\r\n");
            out.write("\t\t\t\t\t\t\tgridPage += 1;\r\n");
            out.write("\t\t\t\t\t\t} else {\r\n");
            out.write("\t\t\t\t\t\t\tgridPage = gridPage;\r\n");
            out.write("\t\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t\t} else if (pgButton == \"prev\") {\r\n");
            out.write("\t\t\t\t\t\tif (gridPage > 1 ){\r\n");
            out.write("\t\t\t\t\t\t\tgridPage -= 1;\r\n");
            out.write("\t\t\t\t\t\t} else {\r\n");
            out.write("\t\t\t\t\t\t\tgridPage = gridPage;\r\n");
            out.write("\t\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t\t} else if (pgButton == \"first\") {\r\n");
            out.write("\t\t\t\t\t\tgridPage = 1;\r\n");
            out.write("                    } else if (pgButton == \"last\") {\r\n");
            out.write("\t\t\t\t\t\tgridPage = lastPage;\r\n");
            out.write("\t\t\t\t\t} else if (pgButton == \"user\") {\r\n");
            out.write("\t\t\t\t\t\tvar nowPage = Number($(\"#pager .ui-pg-input\").val());\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\tif (totalPage >= nowPage && nowPage > 0 ) {\r\n");
            out.write("\t\t\t\t\t\t\tgridPage = nowPage;\r\n");
            out.write("\t\t\t\t\t\t} else {\r\n");
            out.write("\t\t\t\t\t\t\t$(\"#pager .ui-pg-input\").val(nowPage);\r\n");
            out.write("\t\t\t\t\t\t\tgridPage = nowPage;\r\n");
            out.write("\t\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t\t} else if (pgButton == \"records\") {\r\n");
            out.write("\t\t\t\t\t\tgridPage = 1;\r\n");
            out.write("\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\tgrid.setGridParam({\r\n");
            out.write("\t\t\t\t\t\tpage : gridPage,\r\n");
            out.write("\t\t\t\t\t\trowNum : $('.ui-pg-selbox option:selected').val(),\r\n");
            out.write("\t\t\t\t\t\tpostData : JSON.stringify({\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\"pageIndex\": gridPage,\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\"searchKeyword\" : $(\"#searchKeyword\").val(),\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\"pageUnit\":$('.ui-pg-selbox option:selected').val()\r\n");
            out.write("\t\t\t\t\t\t\t\t\t})\r\n");
            out.write("\t\t\t\t\t}).trigger(\"reloadGrid\");\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\tonSelectRow : function(rowId) {\r\n");
            out.write("\t\t\t\t\t// 체크 할떄\r\n");
            out.write("\t\t\t\t\tif(rowId != null) {  \r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\tondblClickRow : function(rowid, iRow, iCol, e) {\r\n");
            out.write("\t\t\t\t\tgrid.jqGrid('editRow', rowid, {keys: true});\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\tonCellSelect : function (rowid, index, contents, action){\r\n");
            out.write("\t\t\t\t\tvar cm = $(this).jqGrid('getGridParam', 'colModel');\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\tif (cm[index].name !='btn'){\r\n");
            out.write("\t\t\t\t\t\tjqGridFunc.fn_resvInfo(\"Edt\", $(this).jqGrid('getCell', rowid, 'resv_seq'));\r\n");
            out.write("\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\t//체크박스 선택시에만 체크박스 체크 적용\r\n");
            out.write("\t\t\t\tbeforeSelectRow: function (rowid, e) { \r\n");
            out.write("\t\t\t\t\tvar $myGrid = $(this), i = $.jgrid.getCellIndex($(e.target).closest('td')[0]), \r\n");
            out.write("\t\t\t\t\tcm = $myGrid.jqGrid('getGridParam', 'colModel'); \r\n");
            out.write("\t\t\t\t\treturn (cm[i].name === 'cb'); \r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t\t});\r\n");
            out.write("\t\t}, \r\n");
            out.write("    \tuseYn : function(cellvalue, options, rowObject) {\r\n");
            out.write("\t\t\treturn (rowObject.use_yn ==  \"Y\") ? \"사용\" : \"사용안함\";\r\n");
            out.write("\t\t},\r\n");
            out.write("\t\tbuttonSetting : function (cellvalue, options, rowObject) {\r\n");
            out.write("\t\t\tvar cancelYn = \"\";\r\n");
            out.write("\t\t\tvar mode = \"\";\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tif(rowObject.blklst_cancel_yn == \"Y\") {\r\n");
            out.write("\t\t\t\tcancelYn = \"재등록\";\r\n");
            out.write("\t\t\t\tmode = \"N\";\r\n");
            out.write("\t\t\t} else {\r\n");
            out.write("\t\t\t\tcancelYn = \"해제\";\r\n");
            out.write("\t\t\t\tmode = \"Y\";\t\t\t\t\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\r\n");
            out.write("\t\t\treturn '<a href=\"javascript:blackUserService.fn_cancelBlklst(&#39;' + mode + '&#39;,&#39;' + rowObject.blklst_seq + '&#39;);\" class=\"blueBtn\">' + cancelYn + '</a>';\t\r\n");
            out.write("\t\t},\t\t\t\r\n");
            out.write("\t\trefreshGrid : function(){\r\n");
            out.write("\t\t\t$('#mainGrid').jqGrid().trigger(\"reloadGrid\");\r\n");
            out.write("\t\t},\r\n");
            out.write("\t\tclearGrid : function() {\r\n");
            out.write("\t\t\t$(\"#mainGrid\").clearGridData();\r\n");
            out.write("\t\t},\r\n");
            out.write("\t\tfn_search: function(){\r\n");
            out.write("\t\t\t$(\"#mainGrid\").setGridParam({\r\n");
            out.write("\t\t\t\tdatatype : \"json\",\r\n");
            out.write("\t\t\t\tpostData : JSON.stringify({\r\n");
            out.write("\t\t\t\t\t\"pageIndex\": $(\"#pager .ui-pg-input\").val(),\r\n");
            out.write("\t\t\t\t\t\"searchBlklstDvsn\" : $(\"#searchBlklstDvsn\").val(),\r\n");
            out.write("\t\t\t\t\t\"searchKeyword\" : $(\"#searchKeyword\").val(),\r\n");
            out.write("\t\t\t\t\t\"searchCondition\" : $(\"#searchCondition\").val(),\r\n");
            out.write("\t\t\t\t\t\"pageUnit\":$('.ui-pg-selbox option:selected').val()\r\n");
            out.write("\t\t\t\t}),\r\n");
            out.write("\t\t\t\tloadComplete : function(data) {\r\n");
            out.write("\t\t\t\t\t$(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);\r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t\t}).trigger(\"reloadGrid\");\r\n");
            out.write(" \t\t}\r\n");
            out.write("\t}\r\n");
            out.write("\t\t\r\n");
            out.write("\tvar blackUserService = {\r\n");
            out.write("\t\tfn_changeBlklstDvsn : function(el){\r\n");
            out.write("\t\t\t$(\"#searchKeyword\").val(\"\");\r\n");
            out.write("\t\t\t$('.ui-pg-selbox option:selected').val(10);\r\n");
            out.write("\t\t\t$(\"#searchBlklstDvsn\").val($(el).attr(\"id\"));\r\n");
            out.write("\t\t\tjqGridFunc.fn_search();\r\n");
            out.write("\t\t},\r\n");
            out.write("\t\tfn_checkForm : function() {\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t},\r\n");
            out.write("\t\tfn_cancelBlklst : function (blklstCancelYn, blklstSeq) {\r\n");
            out.write("\t\t\t$(\"#mode\").val(\"Edt\");\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tvar url = \"/backoffice/rsv/updateBlackUserInfo.do\";\r\n");
            out.write("\t\t\tvar params = {\"mode\" : $(\"#mode\").val(), \"blklstSeq\" : blklstSeq ,\"blklstCancelYn\" : blklstCancelYn};\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tfn_Ajax\r\n");
            out.write("\t\t\t(\r\n");
            out.write("\t\t\t\turl, \r\n");
            out.write("\t\t\t\t\"POST\",\r\n");
            out.write("\t\t\t\tparams,\r\n");
            out.write("\t\t\t\tfalse,\r\n");
            out.write("\t\t\t\tfunction(result) {\r\n");
            out.write("\t\t\t\t\tif (result.status == \"LOGIN FAIL\") {\r\n");
            out.write("\t\t\t\t\t\tcommon_popup(result.meesage, \"Y\",\"\");\r\n");
            out.write("\t\t\t\t\t\tlocation.href=\"/backoffice/login.do\";\r\n");
            out.write("\t\t\t    \t} else if (result.status == \"SUCCESS\") {\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\tfunction(request){\r\n");
            out.write("\t\t\t\t\tcommon_popup(\"Error:\" + request.status,\"\");\r\n");
            out.write("\t\t\t\t}    \t\t\r\n");
            out.write("\t\t\t);\r\n");
            out.write("\t\t},\r\n");
            out.write("\t\tfn_searchResult : function (searchDvsn){\r\n");
            out.write("\t\t\tvar setHtml = \"<table id='searchResultTable' class='whiteBox main_table'>\";\r\n");
            out.write("\t\t\t$(\"#searchResult\").empty();\r\n");
            out.write("\t\t\t$(\"#searchResult\").append(setHtml);\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tvar checkTag = \"\";\r\n");
            out.write("\t\t\tvar colModel = \"\";\r\n");
            out.write("\t\t\tvar gridEmp = $(\"#searchResultTable\");\r\n");
            out.write("\t\t\tvar postData = \"\";\r\n");
            out.write("\t\t\tvar url = \"\";\r\n");
            out.write("\t\t\tgridEmp.jqGrid('clearGridData',true);\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tif(searchDvsn == \"user\") {\r\n");
            out.write("\t\t\t\turl =\"/backoffice/cus/userListAjax.do\";\r\n");
            out.write("\t\t\t\tcheckTag = \"userSearchKeyword\";\r\n");
            out.write("\t\t\t\tcolModel =\r\n");
            out.write("\t\t\t\t[\r\n");
            out.write("\t\t\t\t\t{ label: '아이디', name:'user_id', index:'user_id', align:'left', width:'150px'},\r\n");
            out.write("\t\t\t\t\t{ label: '이름',  name:'user_nm', index:'user_nm', align:'left', width:'150px'},\r\n");
            out.write("\t\t\t\t\t{ label: '전화번호', name:'user_phone', index:'user_phone', align:'left', width:'150px'},\r\n");
            out.write("\t\t\t\t];\r\n");
            out.write("\t\t\t\tpostData = {\"pageIndex\": \"1\", \"mode\": \"\", \"searchCondition\" : $(\"#userSearchCondition\").val(), \"searchKeyword\" : $(\"#userSearchKeyword\").val()};\r\n");
            out.write("\t\t\t} else {\r\n");
            out.write("\t\t\t\turl = \"/backoffice/mng/empListAjax.do\";\r\n");
            out.write("\t\t\t\tcheckTag = \"empSearchKeyword\";\r\n");
            out.write("\t\t\t\tcolModel =\r\n");
            out.write("\t\t\t\t[\r\n");
            out.write("\t\t\t\t\t{ label: '부서', name:'dept_nm', index:'dept_nm', align:'left', width:'150px'},\r\n");
            out.write("\t\t\t\t\t{ label: '사번', name:'emp_no', index:'emp_no', align:'left', width:'150px'},\r\n");
            out.write("\t\t\t\t\t{ label: '이름', name:'emp_nm', index:'emp_nm', align:'left', width:'150px'},\r\n");
            out.write("\t\t\t\t\t{ label: '전화번호', name:'emp_clphn', index:'emp_clphn', align:'left', width:'0px', hidden:true},\r\n");
            out.write("\t\t\t\t\t{ label: '이메일', name:'emp_email', index:'emp_email', align:'left', width:'0px', hidden:true}\r\n");
            out.write("\t\t\t\t];\r\n");
            out.write("\t\t\t\tpostData = {\"pageIndex\": \"1\", \"mode\": \"search\", \"searchCondition\" : $(\"#empSearchCondition\").val(), \"searchKeyword\" : $(\"#empSearchKeyword\").val()};\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tif (any_empt_line_span(\"blacklist_add\", checkTag, \"검색어를 입력해 주세요.\",\"sp_message\", \"savePage\") == false) return;\t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t$(\"#search_result\").bPopup();\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tgridEmp.jqGrid({\r\n");
            out.write("\t\t\t\turl : url,\r\n");
            out.write("\t\t\t\tmtype :  'POST',\r\n");
            out.write("\t\t\t\tdatatype :'json',\r\n");
            out.write("\t\t\t\tajaxGridOptions: { contentType: \"application/json; charset=UTF-8\" },\r\n");
            out.write("\t\t\t\tajaxRowOptions: { contentType: \"application/json; charset=UTF-8\", async: true },\r\n");
            out.write("\t\t\t\tajaxSelectOptions: { contentType: \"application/json; charset=UTF-8\", dataType: \"JSON\" }, \r\n");
            out.write("\t\t\t\tpostData : JSON.stringify( postData ),\r\n");
            out.write("\t\t\t\tjsonReader : {\r\n");
            out.write("\t\t\t\t\troot : 'resultlist',\r\n");
            out.write("\t\t\t\t\t\"page\":\"paginationInfo.currentPageNo\",\r\n");
            out.write("\t\t\t\t\t\"total\":\"paginationInfo.totalPageCount\",\r\n");
            out.write("\t\t\t\t\t\"records\":\"paginationInfo.totalRecordCount\",\r\n");
            out.write("\t\t\t\t\trepeatitems:false\r\n");
            out.write("\t\t\t\t},\r\n");
            out.write("\t\t\t\tcolModel : colModel,  //상단면 \r\n");
            out.write("\t\t\t\trowNum : 1000,  //레코드 수\r\n");
            out.write("\t\t\t\trefresh : false,\r\n");
            out.write("\t\t\t\trownumbers : false, // 리스트 순번\r\n");
            out.write("\t\t\t\tviewrecord : true,    // 하단 레코드 수 표기 유무\r\n");
            out.write("\t\t\t    loadui : \"enable\",\r\n");
            out.write("\t\t\t    loadtext:'데이터를 가져오는 중...',\r\n");
            out.write("\t\t\t    emptyrecords : \"조회된 데이터가 없습니다\", //빈값일때 표시 \r\n");
            out.write("\t\t\t    height : \"100%\",\r\n");
            out.write("\t\t\t    autowidth:false,\r\n");
            out.write("\t\t\t    frozen:true, \r\n");
            out.write("\t\t\t    shrinkToFit : false,\r\n");
            out.write("\t\t\t    refresh : true,\r\n");
            out.write("\t\t\t    multiselect:false,\r\n");
            out.write("\t\t\t    loadonce : true,\r\n");
            out.write("\t\t\t    loadComplete : function (data){\r\n");
            out.write("\t\t\t    \t//완료 표시 \r\n");
            out.write("\t\t\t    }, \r\n");
            out.write("\t\t\t    loadError:function(xhr, status, error) {\r\n");
            out.write("\t\t\t    \tloadtext:'시스템 장애... '\r\n");
            out.write("\t\t\t    }, \r\n");
            out.write("\t\t\t\tonSelectRow: function(rowId){\r\n");
            out.write("\t\t\t\t\tif(rowId != null) {  }// 체크 할떄\r\n");
            out.write("\t\t\t\t}, \r\n");
            out.write("\t\t\t\tonCellSelect : function (rowid, index, contents, action){\r\n");
            out.write("\t\t\t\t\tvar cm = $('#searchResultTable').jqGrid('getGridParam', 'colModel');\r\n");
            out.write("\t\t\t\t\t//console.log(cm);\r\n");
            out.write("\t\t\t\t\tif (cm[index].name !='btn' ){\r\n");
            out.write("\t\t\t\t\t\tblackUserService.fn_inSearchInfo(\t\r\n");
            out.write("\t\t\t\t\t\t\t$(this).jqGrid('getCell', rowid, 'user_id'),\r\n");
            out.write("\t\t\t\t\t\t\t$(this).jqGrid('getCell', rowid, 'user_nm'),\r\n");
            out.write("\t\t\t\t\t\t\t$(this).jqGrid('getCell', rowid, 'user_phone')\r\n");
            out.write("\t\t\t\t\t\t);\r\n");
            out.write("\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t\t});\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\t//추후 변경 예정 \r\n");
            out.write("\t\t\t$(\"#searchResultTable\").setGridParam({\r\n");
            out.write("\t\t\t\tdatatype : \"json\",\r\n");
            out.write("\t\t\t\tpostData : JSON.stringify(postData),\r\n");
            out.write("\t\t\t\tloadComplete : function(data) {}\r\n");
            out.write("\t\t\t}).trigger(\"reloadGrid\");\r\n");
            out.write("\t\t},\r\n");
            out.write("\t\tfn_inSearchInfo : function(userId,userNm,userPhone) {\r\n");
            out.write("\t\t\t$(\"#userId\").val(userId);\r\n");
            out.write("\t\t\t$(\"#userNm\").val(userNm);\r\n");
            out.write("\t\t\t$(\"#userPhone\").val(userPhone);\r\n");
            out.write("\t\t\t$(\"#search_result\").bPopup().close();\r\n");
            out.write("\t\t\t$(\"#blacklist_add\").bPopup();\r\n");
            out.write("\t\t}\r\n");
            out.write("\t}\r\n");
            out.write("</script>\r\n");
            out.write("\r\n");
            if (_jspx_meth_c_005fimport_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("<script type=\"text/javascript\" src=\"/resources/js/back_common.js\"></script>\r\n");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/rsv/blackList.jsp(65,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/backoffice/inc/top_inc.do");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/rsv/blackList.jsp(512,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/backoffice/inc/popup_common.do");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
