/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-11-30 06:17:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.front.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"/resources/css/front/reset.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <script src=\"/resources/js/front/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <link href=\"/resources/css/front/common.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/front/mobile.css\">\r\n");
      out.write("    <!--check box _ css-->\r\n");
      out.write("    <link href=\"/resources/css/front/magic-check.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <title>경륜경정 스마트 입장예약</title>\r\n");
      out.write("    <!-- DatePicker-->\r\n");
      out.write("    <script src=\"/resources/js/front/jquery-ui.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/front/jquery-ui.css\">\r\n");
      out.write("    <!-- Link Swiper's CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/front/swiper.min.css\">\r\n");
      out.write("    <!-- popup-->    \r\n");
      out.write("    <script src=\"/resources/js/front/bpopup.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <!-- // 예약취소 팝업 -->\r\n");
      out.write("    <div data-popup=\"rsv_cancle_pop\" class=\"popup\">\r\n");
      out.write("      <div class=\"pop_con rsv_popup\">\r\n");
      out.write("          <a class=\"button b-close\">X</a>\r\n");
      out.write("          <div class=\"pop_wrap\">\r\n");
      out.write("              <h4>예약 취소 하시겠습니까?</h4>\r\n");
      out.write("              <p>(재예약 시 동일한 좌석으로 예약이 불가할 수 있습니다.)</p>\r\n");
      out.write("\r\n");
      out.write("               <ul class=\"rsv_list\">\r\n");
      out.write("                   <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>예약번호</li>\r\n");
      out.write("                            <li><span class=\"rsv_num\">123458960</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>지점</li>\r\n");
      out.write("                            <li><span class=\"rsv_brch\">대전지점</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>좌석</li>\r\n");
      out.write("                            <li><span class=\"rsv_seat\">A-3F-001</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>일시</li>\r\n");
      out.write("                            <li><span class=\"rsv_date\">2021-12-01 12:00</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li> \r\n");
      out.write("               </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t  <div class=\"cancel_btn\">\r\n");
      out.write("              <a href=\"\" class=\"grayBtn\">예약취소</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clear\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- 최근입장정보 팝업 // -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- // 예약정보 팝업 -->\r\n");
      out.write("\t<div id=\"rsv_info\" class=\"popup\">\r\n");
      out.write("\t\t<div class=\"pop_con rsv_popup\">\r\n");
      out.write("\t\t\t<a class=\"button b-close\">X</a>\r\n");
      out.write("          \t<div class=\"pop_wrap\">\r\n");
      out.write("\t\t\t\t<h4><span class=\"name\"></span>님의 예약 정보 입니다.</h4>\r\n");
      out.write("              \t<p>15시 까지 미 입장시 입장예약이 취소됩니다.</p>\r\n");
      out.write("\r\n");
      out.write("               \t<ul class=\"rsv_list\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("                            <li>지점</li>\r\n");
      out.write("                            <li><span id=\"rsv_center\" class=\"rsv_brch\">대전지점</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>좌석</li>\r\n");
      out.write("                            <li><span id=\"rsv_seat\" class=\"rsv_seat\">A-3F-001</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>일시</li>\r\n");
      out.write("                            <li><span id=\"rsv_date\" class=\"rsv_date\">2021-12-01 12:00</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"cancel_btn\">\r\n");
      out.write("              \t<a href=\"javascript:common_modelClose('rsv_info');\" class=\"grayBtn\">확인</a>\r\n");
      out.write("          \t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 예약정보 팝업 // -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- // 예약취소 팝업 -->\r\n");
      out.write("    <div id=\"cancel_rsv_info\" class=\"popup\">\r\n");
      out.write("      <div class=\"pop_con rsv_popup\">\r\n");
      out.write("          <a class=\"button b-close\">X</a>\r\n");
      out.write("          <div class=\"pop_wrap\">\r\n");
      out.write("              <h4>예약 취소 하시겠습니까?</h4>\r\n");
      out.write("              <p>15시 까지 미 입장시 입장예약이 취소됩니다.</p>\r\n");
      out.write("\r\n");
      out.write("               <ul class=\"rsv_list\">\r\n");
      out.write("                   <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>예약번호</li>\r\n");
      out.write("                            <li><span id=\"cancel_rsv_num\" class=\"rsv_num\">123458960</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>지점</li>\r\n");
      out.write("                            <li><span id=\"cancel_rsv_brch\" class=\"rsv_brch\">대전지점</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>좌석</li>\r\n");
      out.write("                            <li><span id=\"cancel_rsv_seat\" class=\"rsv_seat\">A-3F-001</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>일시</li>\r\n");
      out.write("                            <li><span id=\"cancel_rsv_date\" class=\"rsv_date\">2021-12-01 12:00</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li> \r\n");
      out.write("               </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"cancle_btn\">\r\n");
      out.write("              <a href=\"\" id=\"resvCancleBtn\" class=\"grayBtn\">예약취소</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clear\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 최근입장정보 팝업 // -->\r\n");
      out.write("    \r\n");
      out.write("\t<!-- // 최근입장정보 팝업 -->\r\n");
      out.write("\t<div id=\"re_rsv_info\" data-popup=\"re_seat\" class=\"popup\">\r\n");
      out.write("\t\t<div class=\"pop_con rsv_popup\">\r\n");
      out.write("\t\t\t<a class=\"button b-close\">X</a>\r\n");
      out.write("          \t<div class=\"pop_wrap\">\r\n");
      out.write("\t\t\t\t<h4><span class=\"name\"></span>님 최근 입장 정보 입니다.</h4>\r\n");
      out.write("              \t<p>(다른 고객님이 선 예약 시 예약이 불가능합니다.)</p>\r\n");
      out.write("\r\n");
      out.write("               \t<ul class=\"rsv_list\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("                            <li>지점</li>\r\n");
      out.write("                            <li><span id=\"re_rsv_center\" class=\"rsv_brch\">대전지점</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>좌석</li>\r\n");
      out.write("                            <li><span id=\"re_rsv_seat\" class=\"rsv_seat\">A-3F-001</span></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li>일시</li>\r\n");
      out.write("                            <li><span id=\"re_rsv_date\" class=\"rsv_date\">2021-12-01 12:00</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"summit_btn\">\r\n");
      out.write("\t\t\t\t<a href=\"\" id=\"rebookBtn\" class=\"mintBtn\">최근 좌석으로 예약하기</a>\r\n");
      out.write("          \t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 최근입장정보 팝업 // -->\r\n");
      out.write("\r\n");
      out.write("    <!-- // 최근입장불가 팝업 -->\r\n");
      out.write("\t<div data-popup=\"none_seat\" class=\"popup\">\r\n");
      out.write("\t\t<div class=\"pop_con rsv_popup\">\r\n");
      out.write("\t\t\t<a class=\"button b-close\">X</a>\r\n");
      out.write("          \t<div class=\"pop_wrap\">\r\n");
      out.write("              \t<h4><span class=\"name\">홍길동</span>님의</h4>\r\n");
      out.write("              \t<p>최근 입장 좌석은 예약이 불가능 합니다. <br> 처음부터 예약 부탁드립니다.</p>\r\n");
      out.write("          \t</div>\r\n");
      out.write("          \t<div class=\"summit_btn\">\r\n");
      out.write("              \t<a href=\"\" class=\"mintBtn\">새로 예약하기</a>\r\n");
      out.write("          \t</div>\r\n");
      out.write("          \t<div class=\"clear\"></div>\r\n");
      out.write("      \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 최근입장불가 팝업 // -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- mainpage.jsp script -->\r\n");
      out.write("    <script>\r\n");
      out.write("    \t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 예약일자생성\r\n");
      out.write("\t\t\tvar test_time = \"1700\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar time = date.format(\"HHmm\");\r\n");
      out.write("\t\t\tvar today = date.format(\"yyyyMMdd\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdate.setDate(date.getDate() +1);\r\n");
      out.write("\t\t\tvar tomorrow = date.format(\"yyyyMMdd\")\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar resvDate = (time < test_time) ? today : tomorrow;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsessionStorage.setItem(\"resvDate\",resvDate);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 메인영역생성\r\n");
      out.write("    \t\tvar userId = $(\"#userId\").val();\r\n");
      out.write("    \t\tmainService.fn_makeUserInfoArea(userId, mainService.fn_makeNoticeArea);\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar mainService =\r\n");
      out.write("\t\t{ \r\n");
      out.write("\t\t\tfn_makeUserInfoArea: function(userId, callback) {\r\n");
      out.write("\t\t\t\tvar userInfoTopArea = $(\"#user_info_top_area\");\r\n");
      out.write("\t\t\t\tvar userInfoBottomArea = $(\"#user_info_bottom_area\");\r\n");
      out.write("\t\t\t\tvar qrEnterArea = $(\"#qr_enter_area\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tuserInfoTopArea.empty();\r\n");
      out.write("\t\t\t\tuserInfoBottomArea.empty();\r\n");
      out.write("\t\t\t\tqrEnterArea.hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 회원일 경우\r\n");
      out.write("\t\t\t\tif(userId != \"\") {\r\n");
      out.write("\t\t\t\t\t// 로그인 상태(회원)\r\n");
      out.write("\t\t\t\t\tvar url = \"/front/userInfo.do\";\r\n");
      out.write("\t\t\t\t\tvar params = { \"userId\" : userId }\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 예약 단계별 화면처리를 위한 sessionStorage\r\n");
      out.write("\t\t\t\t\t// loginType : 회원 -> 1  비회원 -> 2 \r\n");
      out.write("\t\t\t\t\tsessionStorage.setItem(\"loginType\",\"1\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfn_Ajax\r\n");
      out.write("\t\t\t\t\t(\r\n");
      out.write("\t\t\t\t\t    url,\r\n");
      out.write("\t\t\t\t\t    \"GET\",\r\n");
      out.write("\t\t\t\t\t\tparams,\r\n");
      out.write("\t\t\t\t\t\tfalse,\r\n");
      out.write("\t\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t\t\t\tif (result.status == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar today = new Date().format(\"yyyy-MM-dd\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar reservationInfo = result.reservationInfo;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar userLoginInfo = result.userLoginInfo;\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t// 마지막 예약정보가 존재할 경우\r\n");
      out.write("\t\t\t\t\t\t\t\tif(result.reservationInfo != null) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar obj = result.reservationInfo;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#user_rsv_area\").addClass(\"main_user_rsv\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(obj.resv_info_type == \"NOW\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#user_rsv_area ul\").addClass(\"member_rsv\");\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 유저정보상단 HTML생성\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar setHtml = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><em class='user_name'>\" + userLoginInfo.userNm + \"</em>님 입장예약 현황. <span class='thvac'></span></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><span class='today_date'>\" + today + \"</span></li>\";  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tuserInfoTopArea.append(setHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 유저정보하단 HTML생성\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><span><a href='javascript:mainService.fn_userResvInfo(&#39;NOW&#39;, &#39;\" + obj.resv_seq + \"&#39;, &#39;rsv_info&#39;);' >\" + obj.center_nm + \" \" + obj.seat_nm + \"</a></span></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li class='rsv_cancle'><a href='javascript:mainService.fn_userResvInfo(&#39;CANCEL&#39;, &#39;\" + obj.resv_seq + \"&#39;, &#39;cancel_rsv_info&#39;);'>예약취소</a></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><em><img src='/resources/img/front/alert_icon.svg' alt='알림'>15시 까지 미 입장시 입장예약이 취소됩니다.</em></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tuserInfoBottomArea.append(setHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 현재 예약정보 팝업창 정보 입력\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#rsv_info .name\").html(userLoginInfo.userNm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#rsv_center\").html(obj.center_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#rsv_seat\").html(obj.seat_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#rsv_date\").html(obj.frst_regist_dtm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 처음부터 예약하기 영역 비활성화\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#rsv_reset_area\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// QR코드 영역 활성화\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(qrEnterArea).show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(qrEnterArea).find(\"a\").attr(\"href\",\"javascript:mainService.fn_moveQrPage('\" + obj.resv_seq + \"');\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 유저정보상단 HTML생성\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar setHtml = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><em class='user_name'>\" + userLoginInfo.userNm + \"</em>님 예약내역이 없습니다. <span class='thvac'></span></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><span class='today_date'>\" + today + \"</span></li>\";  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tuserInfoTopArea.append(setHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 유저정보하단 HTML생성\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><span><a href='javascript:mainService.fn_userResvInfo(&#39;PRE&#39;, &#39;\" + obj.resv_seq + \"&#39;,&#39;re_rsv_info&#39;);' >다시 앉기<img src='/resources/img/front/arrow.png' alt='예약하기'></a></span></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsetHtml += \"<li><em><img src='/resources/img/front/alert_icon.svg' alt='알림'>과거 예약한 정보로 다시 앉으실 수 있습니다.</em></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tuserInfoBottomArea.append(setHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 다시앉기 팝업창 정보 입력\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// TODO 추후 제거\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#re_rsv_info .name\").html(userLoginInfo.userNm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#re_rsv_center\").html(obj.center_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#re_rsv_seat\").html(obj.seat_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#re_rsv_date\").html(obj.resv_req_date);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 처음부터 예약하기 영역 활성화\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#rsv_reset_area\").show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#user_rsv_area\").addClass(\"main_user_rsv\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// 유저정보상단 HTML생성\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar setHtml = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsetHtml += \"<li><em class='user_name'>\" + userLoginInfo.userNm + \"</em>님 예약내역이 없습니다. <span class='thvac'></span></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsetHtml += \"<li><span class='today_date'>\" + today + \"</span></li>\";  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tuserInfoTopArea.append(setHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// 유저정보하단 HTML생성\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsetHtml = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsetHtml += \"<li><span><a href='/front/rsvCenter.do'>빠르게 예약하기<img src='/resources/img/front/arrow.png' alt='예약하기'></a></span></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tuserInfoBottomArea.append(setHtml);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// 처음부터 예약하기 영역 활성화\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rsv_reset_area\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t} else if(result.status == \"LOGINFAIL\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tfunction(request) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"ERROR : \" +request.status);\t       \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t\t\t);\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t// 비로그인 상태(비회원)\r\n");
      out.write("\t\t\t\t\t$(\"#user_rsv_area\").addClass(\"main_user_rsv\");\r\n");
      out.write("\t\t\t\t\t$(\".main_user_pad\").addClass(\"non_mem\");\r\n");
      out.write("\t\t\t\t\t$(\".mo_user_info_txt\").addClass(\"non_border\");\r\n");
      out.write("\t\t\t\t\t$(userInfoBottomArea).addClass(\"non_member\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 유저정보상단 HTML생성\r\n");
      out.write("\t\t\t\t\tvar setHtml = \"\";\r\n");
      out.write("\t\t\t\t\tsetHtml += \"<li>오늘도 즐거운 하루 보내세요!</li>\";\r\n");
      out.write("\t\t\t\t\tuserInfoTopArea.append(setHtml);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 유저정보하단 HTML생성\r\n");
      out.write("\t\t\t\t\tsetHtml = \"\";\r\n");
      out.write("\t\t\t\t\tsetHtml += \"<li><a href='/front/login.do'>로그인</a></li>\";\r\n");
      out.write("\t\t\t\t\tsetHtml += \"<li><a href='javascript:fn_moveReservation();'>비회원 예약</a></li>\";\r\n");
      out.write("\t\t\t\t\tuserInfoBottomArea.append(setHtml);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfn_userResvInfo : function(division, resvSeq, popup) {\t\t\t\t\r\n");
      out.write("\t\t\t\tvar url = \"/front/userResvInfo.do\";\r\n");
      out.write("\t\t\t\tvar params = {\r\n");
      out.write("\t\t\t\t\t\"resvSeq\" : resvSeq,\r\n");
      out.write("\t\t\t\t\t\"resvDate\" : sessionStorage.getItem(\"resvDate\"),\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfn_Ajax\r\n");
      out.write("\t\t\t\t(\r\n");
      out.write("\t\t\t\t    url,\r\n");
      out.write("\t\t\t\t    \"POST\",\r\n");
      out.write("\t\t\t\t\tparams,\r\n");
      out.write("\t\t\t\t\tfalse,\r\n");
      out.write("\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t    \tconsole.log(result);\r\n");
      out.write("\t\t\t\t    \tif (result.status == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t    \t\tif(result.resultlist != null) {\r\n");
      out.write("\t\t\t\t    \t\t\tvar obj = result.resultlist;\r\n");
      out.write("\t\t\t\t    \t\t\tvar userLoginInfo = result.userLoginInfo;\r\n");
      out.write("\t\t\t\t    \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif(division == \"NOW\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rsv_info .name\").html(userLoginInfo.userNm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rsv_center\").html(obj.center_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rsv_seat\").html(obj.seat_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rsv_date\").html(obj.frst_regist_dtm);\r\n");
      out.write("\t\t\t\t\t\t\t\t} else if(division == \"PRE\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#re_rsv_info .name\").html(userLoginInfo.userNm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#re_rsv_center\").html(obj.center_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#re_rsv_seat\").html(obj.seat_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#re_rsv_date\").html(obj.resv_req_date);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar rebookBtnText = obj.re_resv_yn == \"Y\" ? \"최근 좌석으로 예약하기\" : \"현재 예약할수 없는 좌석입니다.\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar rebookBtnHref = obj.re_resv_yn == \"Y\" ? \"mainService.fn_rebook('\" + obj.resv_seq + \"');\" : \"void(0);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar rebookBtnColor = obj.re_resv_yn == \"Y\" ? \"#47D6BE\" : \"#808080\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rebookBtn\").css(\"background\",rebookBtnColor);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rebookBtn\").html(rebookBtnText)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#rebookBtn\").attr(\"href\",\"javascript:\" + rebookBtnHref);\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#cancel_rsv_info .name\").html(userLoginInfo.userNm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#cancel_rsv_num\").html(obj.resv_seq);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#cancel_rsv_center\").html(obj.center_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#cancel_rsv_seat\").html(obj.seat_nm);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#cancel_rsv_date\").html(obj.resv_req_date);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#resvCancleBtn\").attr(\"href\",\"javascript:mainService.fn_resvCancel('\" + obj.resv_seq + \"');\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    \t\t}\r\n");
      out.write("\t\t\t\t    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#resvSeq\").val(resvSeq);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#\" + popup).bPopup();\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"error\")\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tfunction(request) {\r\n");
      out.write("\t\t\t\t\t\talert(\"ERROR : \" + request.status);\t       \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t\t);\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfn_resvCancel : function(resvSeq) {\r\n");
      out.write("\t\t\t\tvar url = \"/front/resvInfoCancel.do\";\r\n");
      out.write("\t\t\t\tvar params = {\r\n");
      out.write("\t\t\t\t\t\"userDvsn\" : $(\"#userDvsn\").val(),\r\n");
      out.write("\t\t\t\t\t\"resvSeq\" : resvSeq\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfn_Ajax\r\n");
      out.write("\t\t\t\t(\r\n");
      out.write("\t\t\t\t    url,\r\n");
      out.write("\t\t\t\t    \"POST\",\r\n");
      out.write("\t\t\t\t\tparams,\r\n");
      out.write("\t\t\t\t\tfalse,\r\n");
      out.write("\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t    \tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\tif (result.status == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"예약이 정상적으로 취소되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t} else if (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(result.message);\r\n");
      out.write("\t\t\t\t\t\t\tlocataion.href = \"/front/main.do\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tfunction(request) {\r\n");
      out.write("\t\t\t\t\t\talert(\"ERROR : \" + request.status);\t       \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t\t);\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfn_rebook : function(resvSeq) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfn_moveQrPage : function(resvSeq) {\r\n");
      out.write("\t\t\t\tlocation.href = \"/front/qrEnter.do?resvSeq=\" + resvSeq;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/resources/js/front/common.js\"></script>\r\n");
      out.write("\t<script src=\"/resources/js/front/front_common.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/front/main/mainpage.jsp(30,1) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("regist");
      // /WEB-INF/jsp/front/main/mainpage.jsp(30,1) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("regist");
      // /WEB-INF/jsp/front/main/mainpage.jsp(30,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/jsp/front/main/mainpage.jsp(30,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("/front/main.do");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t<input type=\"hidden\" id=\"userDvsn\" name=\"userDvsn\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLoginInfo.userDvsn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\">\r\n");
            out.write("\t<input type=\"hidden\" name=\"userId\" id=\"userId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLoginInfo.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\">\r\n");
            out.write("\t<input type=\"hidden\" name=\"resvSeq\" id=\"resvSeq\" value=\"\">\r\n");
            out.write("\r\n");
            out.write("\t<div class=\"wrapper mainBack\">\r\n");
            out.write("\t\t<!--// header -->\r\n");
            out.write("        <div id=\"header\"></div>\r\n");
            out.write("        <!-- header //-->\r\n");
            out.write("        <!--// contents-->\r\n");
            out.write("        <div id=\"container\">\r\n");
            out.write("            <div class=\"contents\">\r\n");
            out.write("                <div class=\"mo_user_info\">\r\n");
            out.write("                    <ul>\r\n");
            out.write("                        <li class=\"slogan\">빠르고 편리하게 입장 신청하세요!</li>\r\n");
            out.write("                        <li class=\"headerImg\"></li>\r\n");
            out.write("                        <li class=\"topImg\"></li>\r\n");
            out.write("                    </ul>                \r\n");
            out.write("                </div>\r\n");
            out.write("\r\n");
            out.write("                <div class=\"main_user\">                  \r\n");
            out.write("                    <div class=\"main_user_info no-reser\">\r\n");
            out.write("                        <div class=\"main_user_pad\">\r\n");
            out.write("                            <div class=\"mo_user_info_txt\">\r\n");
            out.write("                                <ul id=\"user_info_top_area\">\r\n");
            out.write("\r\n");
            out.write("                                </ul>\r\n");
            out.write("                            </div>                            \r\n");
            out.write("\r\n");
            out.write("                            <div class=\"clear\"></div>\r\n");
            out.write("                            <div id=\"user_rsv_area\">\r\n");
            out.write("                                <ul id=\"user_info_bottom_area\">\r\n");
            out.write("\r\n");
            out.write("                                    <li class=\"rsv_cancle\"><a data-popup-open=\"rsv_cancle_pop\">예약취소</a></li>\r\n");
            out.write("\r\n");
            out.write("                                </ul>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"clear\"></div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                    \r\n");
            out.write("                </div>\r\n");
            out.write("\r\n");
            out.write("                <div id=\"qr_enter_area\" class=\"qr_enter\" style=\"display:none;\">\r\n");
            out.write("                    <ul>\r\n");
            out.write("                        <li>QR 입장</li>\r\n");
            out.write("                        <li class=\"qr_code\"><a href=\"\"><img src=\"/resources/img/front/qr_code.svg\" alt=\"qr코드\"></a></li>\r\n");
            out.write("                    </ul>\r\n");
            out.write("                </div>\r\n");
            out.write("\t\t\t\t<div id=\"rsv_reset_area\" class=\"rsv_reset\" style=\"display:none;\">\r\n");
            out.write("                    <ul>\r\n");
            out.write("                        <li>처음부터 예약하시려면</li>\r\n");
            out.write("                        <li class=\"reservation\"><a href=\"javascript:fn_moveReservation();\">예약하기</a></li>\r\n");
            out.write("                    </ul>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("        </div>\r\n");
            out.write("        <!--contents //-->\r\n");
            out.write("        <!--// footer -->\r\n");
            out.write("        <div id=\"footer\">\r\n");
            out.write("            <div class=\"contents\">\r\n");
            out.write("                <div class=\"main_notice\">\r\n");
            out.write("                    <div class=\"footer_tit\">\r\n");
            out.write("                        <h2><span class=\"branch\">분당지점</span>공지사항</h2>\r\n");
            out.write("                        <a href=\"\" class=\"main_noti_link\">더보기</a>\r\n");
            out.write("                        <div class=\"clear\"></div>\r\n");
            out.write("                    </div>\r\n");
            out.write("\r\n");
            out.write("                    <!-- 공지사항 데이터 -->\r\n");
            out.write("                    <div class=\"main_noti_list\">\r\n");
            out.write("                        <div class=\"notice_con\">                            \r\n");
            out.write("                            <p class=\"notice_date\">2021.12.01</p>\r\n");
            out.write("                            <p class=\"notice_tit\"><span>코로나 19 방역에 따라 경기 일정이 변경 되었습니다.</span></p>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <!--공지사항 내용 -->\r\n");
            out.write("                        <div class=\"notice_inner\">\r\n");
            out.write("                            \t코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나코로나 19 방역 수칙에 따른 이용자 명부 작성 필수 코로나\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                    <div>\r\n");
            out.write("                        <div class=\"notice_con\">                           \r\n");
            out.write("                            <p class=\"notice_date\">2021.12.01</p>\r\n");
            out.write("                            <p class=\"notice_tit\"><span>[공지] 코로나 19 방역수칙에 따른 이용자 명부 작성을 의무화합니다.</span></p>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <!--공지사항 내용 -->\r\n");
            out.write("                        <div class=\"notice_inner\">내용 \r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>   \r\n");
            out.write("                    <div>\r\n");
            out.write("                        <div class=\"notice_con\">                            \r\n");
            out.write("                            <p class=\"notice_date\">2021.12.01</p>\r\n");
            out.write("                            <p class=\"notice_tit\"><span>[공지] 시스템 개선 및 점검 안내</span></p>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <!--공지사항 내용 -->\r\n");
            out.write("                        <div class=\"notice_inner\">내용\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>                     \r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"f_logo_box\">\r\n");
            out.write("                <div class=\"contents\">\r\n");
            out.write("                    <p class=\"f_copy\">Copyright</p>\r\n");
            out.write("                    <div class=\"clear\"></div>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("        </div>\r\n");
            out.write("        <!-- footer //-->\r\n");
            out.write("\r\n");
            out.write("        <div id=\"foot_btn\">\r\n");
            out.write("            <div class=\"contents\">\r\n");
            out.write("                <ul>\r\n");
            out.write("                    <li class=\"home active\"><a href=\"/front/main.do\">home</a><span>HOME</span></li>\r\n");
            out.write("                    <li class=\"rsv\"><a href=\"javascript:fn_moveReservation();\">rsv</a><span>입장예약</span></li>\r\n");
            out.write("                    <li class=\"my\"><a href=\"javascript:fn_pageMove('regist','/front/mypage.do');\">my</a><span>마이페이지</span></li>\r\n");
            out.write("                </ul>\r\n");
            out.write("                <div class=\"clear\"></div>\r\n");
            out.write("            </div>\r\n");
            out.write("        </div>\r\n");
            out.write("    </div>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }
}
