/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-11-30 08:14:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backoffice.bas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kioskList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no;\" />\r\n");
      out.write("    <title>경륜경정 스마트입장 관리자</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/reset.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/paragraph.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\" />\r\n");
      out.write("    <script src=\"/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/bpopup.js\"></script>\r\n");
      out.write("    <!-- datepicker-->\r\n");
      out.write("    <script src=\"/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("    <!-- 체크 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/jquery-ui.css\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"/css/jquery-ui.css\"> -->\r\n");
      out.write("    \r\n");
      out.write("   \t<script src=\"/resources/js/common.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jqGrid -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/jqgrid/src/css/ui.jqgrid.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/src/i18n/grid.locale-kr.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery.browser = {};\r\n");
      out.write("\t\t(function () {\r\n");
      out.write("\t\t    jQuery.browser.msie = false;\r\n");
      out.write("\t\t    jQuery.browser.version = 0;\r\n");
      out.write("\t\t    if (navigator.userAgent.match(/MSIE ([0-9]+)\\./)) {\r\n");
      out.write("\t\t        jQuery.browser.msie = true;\r\n");
      out.write("\t\t        jQuery.browser.version = RegExp.$1;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t})();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t    .ui-jqgrid .ui-jqgrid-htable th div{\r\n");
      out.write("\t\t\toutline-style: none;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t    .ui-jqgrid tr.jqgrow {\r\n");
      out.write("\t\t\toutline-style: none;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("    </style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() { \r\n");
      out.write("\t\t\tjqGridFunc.setGrid(\"mainGrid\");\r\n");
      out.write("\t \t});\r\n");
      out.write("    \t\r\n");
      out.write("\t\tvar jqGridFunc  = \r\n");
      out.write("\t\t{\r\n");
      out.write("    \t\tsetGrid : function(gridOption) {\r\n");
      out.write("    \t\t\tvar grid = $('#'+gridOption);\r\n");
      out.write("    \t\t    //ajax 관련 내용 정리 하기 \r\n");
      out.write("    \t\t\t\r\n");
      out.write("                var postData = {};\r\n");
      out.write("    \t\t    grid.jqGrid({\r\n");
      out.write("    \t\t    \turl : '/backoffice/bas/kioskListAjax.do' ,\r\n");
      out.write("    \t\t        mtype :  'POST',\r\n");
      out.write("    \t\t        datatype :'json',\r\n");
      out.write("    \t\t        pager: $('#pager'),  \r\n");
      out.write("    \t\t        ajaxGridOptions: { contentType: \"application/json; charset=UTF-8\" },\r\n");
      out.write("    \t\t        ajaxRowOptions: { contentType: \"application/json; charset=UTF-8\", async: true },\r\n");
      out.write("    \t\t        ajaxSelectOptions: { contentType: \"application/json; charset=UTF-8\", dataType: \"JSON\" }, \r\n");
      out.write("    \t\t       \r\n");
      out.write("    \t\t        postData :  JSON.stringify(postData),\r\n");
      out.write("    \t\t        jsonReader : \r\n");
      out.write("    \t\t        {\r\n");
      out.write("\t\t\t\t\t\troot : 'resultlist',\r\n");
      out.write("\t\t\t\t\t\t\"page\":\"paginationInfo.currentPageNo\",\r\n");
      out.write("\t\t\t\t\t\t\"total\":\"paginationInfo.totalPageCount\",\r\n");
      out.write("\t\t\t\t\t\t\"records\":\"paginationInfo.totalRecordCount\",\r\n");
      out.write("\t\t\t\t\t\trepeatitems:false\r\n");
      out.write("   \t\t            },\r\n");
      out.write("   \t\t         \t//상단면\r\n");
      out.write("    \t\t        colModel :  \r\n");
      out.write("\t\t\t\t\t[\r\n");
      out.write("\t\t\t\t\t\t{ label: '무인발권기 Serial',  name:'ticket_mchn_sno', index:'ticket_mchn_sno', align:'center', width:'15%', key:true},\r\n");
      out.write("\t\t\t\t\t\t{ label: '지점명',  name:'center_nm', index:'center_cd', align:'center', width:'10%'},\r\n");
      out.write("\t\t\t\t\t\t{ label: '사용 층수', name:'floor_nm', index:'floor_cd', align:'center', width:'15%'},\r\n");
      out.write("\t\t\t\t\t\t{ label: '위치', name:'ticket_mchn_remark', index:'ticket_mchn_remark', align:'center', width:'15%'},\r\n");
      out.write("\t\t\t\t\t\t{ label: '사용 여부', name:'use_yn', index:'use_yn', align:'center', width:'40%'},\r\n");
      out.write("\t\t\t\t\t\t{ label: '수정일자', name:'last_updt_dtm', index:'last_updt_dtm', align:'center', width:'10%'},\r\n");
      out.write("\t\t\t\t\t\t{ label: '수정자', name: 'last_updusr_id',  index:'last_updusr_id', align:'center', width: '10%'}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t//레코드 수\r\n");
      out.write("    \t\t        rowNum : 10,\r\n");
      out.write("    \t\t     \t// 페이징 수\r\n");
      out.write("    \t\t        rowList : [10,20,30,40,50,100],  \r\n");
      out.write("    \t\t        pager : pager,\r\n");
      out.write("    \t\t        refresh : true,\r\n");
      out.write("    \t\t     \t// 리스트 순번\r\n");
      out.write("    \t            rownumbers : false,\r\n");
      out.write("    \t         \t// 하단 레코R드 수 표기 유무\r\n");
      out.write("    \t\t        viewrecord : true,\r\n");
      out.write("    \t\t     \t// true 데이터 한번만 받아옴\r\n");
      out.write("    \t\t        //loadonce : false,      \r\n");
      out.write("    \t\t        loadui : \"enable\",\r\n");
      out.write("    \t\t        loadtext:'데이터를 가져오는 중...',\r\n");
      out.write("    \t\t      \t//빈값일때 표시\r\n");
      out.write("    \t\t        emptyrecords : \"조회된 데이터가 없습니다\", \r\n");
      out.write("    \t\t        height : \"100%\",\r\n");
      out.write("    \t\t        autowidth:true,\r\n");
      out.write("    \t\t        shrinkToFit : true,\r\n");
      out.write("    \t\t        refresh : true,\r\n");
      out.write("    \t\t        multiselect: true,\r\n");
      out.write("    \t\t        loadComplete : function (data){\r\n");
      out.write("    \t\t        \t$(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);\r\n");
      out.write("    \t\t        },\r\n");
      out.write("    \t\t        beforeSelectRow: function (rowid, e) {\r\n");
      out.write("    \t\t            var $myGrid = $(this);\r\n");
      out.write("    \t\t            var i = $.jgrid.getCellIndex($(e.target).closest('td')[0]);\r\n");
      out.write("    \t\t            var cm = $myGrid.jqGrid('getGridParam', 'colModel');\r\n");
      out.write("    \t\t            return (cm[i].name == 'cb'); // 선택된 컬럼이 cb가 아닌 경우 false를 리턴하여 체크선택을 방지\r\n");
      out.write("    \t\t        },\r\n");
      out.write("    \t\t        loadError:function(xhr, status, error) {\r\n");
      out.write("    \t\t            alert(error); \r\n");
      out.write("    \t\t        }, \r\n");
      out.write("    \t\t        onPaging: function(pgButton){\r\n");
      out.write("\t\t\t\t\t\tvar gridPage = grid.getGridParam('page'); //get current  page\r\n");
      out.write("\t\t\t\t\t\tvar lastPage = grid.getGridParam(\"lastpage\"); //get last page \r\n");
      out.write("\t\t\t\t\t\tvar totalPage = grid.getGridParam(\"total\");\r\n");
      out.write("    \t\t              \r\n");
      out.write("\t\t\t\t\t\tif (pgButton == \"next\"){\r\n");
      out.write("\t\t\t\t\t\t\t/* gridPage = gridPage < lastPage ? gridPage +=1 : gridPage; */\r\n");
      out.write("\t\t\t\t\t\t\tif (gridPage < lastPage ){\r\n");
      out.write("\t\t\t\t\t\t\t\tgridPage += 1;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tgridPage = gridPage;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t} else if (pgButton == \"prev\") {\r\n");
      out.write("\t\t\t\t\t\t\t/* gridPage = gridPage > 1 ? gridPage -=1 : gridPage; */\r\n");
      out.write("\t\t\t\t\t\t\tif (gridPage > 1 ) {\r\n");
      out.write("\t\t\t\t\t\t\t\tgridPage -= 1;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tgridPage = gridPage;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t} else if (pgButton == \"first\"){\r\n");
      out.write("\t\t\t\t\t\t\tgridPage = 1;\r\n");
      out.write("\t\t\t\t\t\t} else if (pgButton == \"last\") {\r\n");
      out.write("\t\t\t\t\t\t\tgridPage = lastPage;\r\n");
      out.write("\t\t\t\t\t\t} else if (pgButton == \"user\"){\r\n");
      out.write("\t\t\t\t\t\t\tvar nowPage = Number($(\"#pager .ui-pg-input\").val());\r\n");
      out.write("    \t\t            \t  \r\n");
      out.write("\t\t\t\t\t\t\tif (totalPage >= nowPage && nowPage > 0 ){\r\n");
      out.write("\t\t\t\t\t\t\t\tgridPage = nowPage;\r\n");
      out.write("    \t\t            \t} else {\r\n");
      out.write("    \t\t            \t\t$(\"#pager .ui-pg-input\").val(nowPage);\r\n");
      out.write("    \t\t            \t\tgridPage = nowPage;\r\n");
      out.write("    \t\t            \t}\r\n");
      out.write("\t\t\t\t\t\t} else if (pgButton == \"records\") {\r\n");
      out.write("    \t\t            \t  gridPage = 1;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tgrid.setGridParam\r\n");
      out.write("\t\t\t\t\t\t({\r\n");
      out.write("\t\t\t\t\t\t\tpage : gridPage,\r\n");
      out.write("\t\t\t\t\t\t\trowNum : $('.ui-pg-selbox option:selected').val(),\r\n");
      out.write("\t\t\t\t\t\t\tpostData : JSON.stringify\r\n");
      out.write("\t\t\t\t\t\t\t({\r\n");
      out.write("\t\t\t\t\t\t\t\t\"pageIndex\": gridPage,\r\n");
      out.write("\t\t\t\t\t\t\t\t\"searchKeyword\" : $(\"#searchKeyword\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\"searchCondition\" : $(\"#searchCondition\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\"searchCenterCd\" : $(\"#searchCenterCd\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\"pageUnit\":$('.ui-pg-selbox option:selected').val()\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t}).trigger(\"reloadGrid\");\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tonSelectRow: function(rowId){\r\n");
      out.write("    \t                if(rowId != null) {  }// 체크 할떄\r\n");
      out.write("    \t            },\r\n");
      out.write("    \t            ondblClickRow : function(rowid, iRow, iCol, e){\r\n");
      out.write("    \t            \tgrid.jqGrid('editRow', rowid, {keys: true});\r\n");
      out.write("    \t            },\r\n");
      out.write("    \t            //셀 선택시 이벤트 등록\r\n");
      out.write("    \t            onCellSelect : function (rowid, index, contents, action) {\r\n");
      out.write("    \t            \tvar cm = $(this).jqGrid('getGridParam', 'colModel');\r\n");
      out.write("    \t                if (cm[index].name != 'cb') {\r\n");
      out.write("    \t                \tjqGridFunc.fn_kioskInfo(\"Edt\", $(this).jqGrid('getCell', rowid, 'ticket_mchn_sno'));\r\n");
      out.write("            \t\t    }\r\n");
      out.write("    \t            }\r\n");
      out.write("    \t\t    });\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \t\trefreshGrid : function() {\r\n");
      out.write("\t\t\t\t$('#mainGrid').jqGrid().trigger(\"reloadGrid\");\r\n");
      out.write("\t       \t},\r\n");
      out.write("\t       \tclearGrid : function() {\r\n");
      out.write("\t\t\t\t$(\"#mainGrid\").clearGridData();\r\n");
      out.write("\t\t\t}, \r\n");
      out.write("\t       \tfn_delCheck  : function(){\r\n");
      out.write("   \t    \t    //체크값 삭제 \r\n");
      out.write("\t       \t\tvar menuArray = new Array();\r\n");
      out.write("  \t\t\t    getEquipArray(\"mainGrid\", menuArray);\r\n");
      out.write("  \t\t\t    if (menuArray.length > 0){\r\n");
      out.write("  \t\t\t\t  $(\"#hid_DelCode\").val(menuArray.join(\",\"))\r\n");
      out.write("  \t\t\t\t  $(\"#id_ConfirmInfo\").attr(\"href\", \"javascript:jqGridFunc.fn_del()\");\r\n");
      out.write("  \t\t\t\t  menuArray = null;\r\n");
      out.write("         \t\t  fn_ConfirmPop(\"삭제 하시겠습니까?\");\r\n");
      out.write("  \t\t\t    }else {\r\n");
      out.write("  \t\t\t\t  menuArray = null;\r\n");
      out.write("  \t\t\t\t  common_modelCloseM(\"체크된 값이 없습니다.\", \"savePage\");\r\n");
      out.write("  \t\t\t    }\r\n");
      out.write("   \t        },\r\n");
      out.write("   \t        fn_del : function (){\r\n");
      out.write("   \t        \tvar params = {'ticketMchnSno':$.trim($(\"#hid_DelCode\").val())};\r\n");
      out.write("   \t        \tfn_uniDelAction(\"/backoffice/bas/kioskDelete.do\", \"GET\", params, false, \"jqGridFunc.fn_search\");\r\n");
      out.write("   \t        },\r\n");
      out.write("           \tfn_kioskInfo : function (mode, ticketMchnSno) {\r\n");
      out.write("           \t\t$(\"#bas_kiosk_add\").bPopup();\r\n");
      out.write("           \t\t$(\"#mode\").val(mode);\r\n");
      out.write("\t\t        if (mode == \"Edt\") {\r\n");
      out.write("\t\t           \tvar params = {\"ticketMchnSno\" : ticketMchnSno};\r\n");
      out.write("\t\t     \t   \tvar url = \"/backoffice/bas/kioskInfoDetail.do\";\r\n");
      out.write("\t\t     \t    $(\"#ticketMchnSno\").val(ticketMchnSno).prop('readonly', true);\r\n");
      out.write("\t\t     \t   \tfn_Ajax\r\n");
      out.write("\t\t     \t   \t(\r\n");
      out.write("\t\t\t\t\t\turl, \r\n");
      out.write("\t\t\t\t\t\t\"GET\",\r\n");
      out.write("\t\t\t\t\t\tparams, \r\n");
      out.write("\t\t\t\t\t\tfalse,\r\n");
      out.write("\t\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t\t\t\tif (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tcommon_modelCloseM(result.meesage, \"Y\", \"bas_holiday_add\");\r\n");
      out.write("\t\t\t\t\t\t\t\tlocation.href=\"/backoffice/login.do\";\r\n");
      out.write("\t\t\t\t\t\t\t} else if (result.status == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t//총 게시물 정리 하기\r\n");
      out.write("\t\t\t\t\t\t\t\tvar obj = result.regist;\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#ticketMchnSno\").val(obj.ticket_mchn_sno);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#targetTicketMchnSno\").val(obj.ticket_mchn_sno);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#centerCd\").val(obj.center_cd);\r\n");
      out.write("\t\t\t\t\t\t\t\tjqGridFunc.fn_floorCombo();\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#floorCd\").val(obj.floor_cd);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"textarea[name=ticketMchnRemark]\").val(obj.ticket_mchn_remark);\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"input:radio[name='useYn']:radio[value='\"+obj.use_yn+\"']\").prop('checked', true);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#sp_Unqi\").hide();\r\n");
      out.write("    \t\t\t\t\t\t    $(\"#btnSave\").text(\"수정\");\r\n");
      out.write("\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t    common_modelCloseM(result.message, \"bas_holiday_add\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tfunction(request){\r\n");
      out.write("\t\t\t\t\t\t\tcommon_modelCloseM(\"ERROR : \" +request.status, \"bas_holiday_add\");\r\n");
      out.write("\t\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t} else {\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#ticketMchnSno\").val(\"\").prop('readonly', false);\r\n");
      out.write("\t\t\t\t\t$(\"#useY\").prop(\"checked\", true);\r\n");
      out.write("\t\t\t\t\t$(\"#centerCd option:eq(0)\").prop(\"selected\", true);\r\n");
      out.write("\t\t\t\t\t$(\"#floorCd option:eq(0)\").prop(\"selected\", true);\r\n");
      out.write("\t\t\t\t\t$(\"textarea[name=ticketMchnRemark]\").val(\"\");\r\n");
      out.write("\t\t\t\t\t$(\"#sp_Unqi\").show();\r\n");
      out.write("\t\t\t\t    $(\"#btnSave\").text(\"등록\");\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t\t$(\"#bas_kiosk_add\").bPopup();\r\n");
      out.write("           \t},\r\n");
      out.write("           \tfn_floorCombo : function(){\r\n");
      out.write("\t\t\t\tif ($(\"#centerCd\").val() != \"\"){\r\n");
      out.write("\t\t\t\t\tvar _url = \"/backoffice/bld/floorComboInfo.do\";\r\n");
      out.write("\t\t\t\t\tvar _params = {\"centerCd\" : $(\"#centerCd\").val()};\r\n");
      out.write("\t\t\t\t\tvar returnVal = uniAjaxReturn(_url, \"GET\", false, _params, \"lst\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (returnVal.length > 0){\r\n");
      out.write("\t\t\t\t        var obj  = returnVal;\r\n");
      out.write("\t\t\t\t\t    $(\"#floorCd\").empty();\r\n");
      out.write("\t\t\t\t\t    $(\"#floorCd\").append(\"<option value=''>선택</option>\");\r\n");
      out.write("\t\t\t\t\t    for (var i in obj) {\r\n");
      out.write("\t\t\t\t\t        var array = Object.values(obj[i])\r\n");
      out.write("\t\t\t\t\t        $(\"#floorCd\").append(\"<option value='\"+ array[0]+\"'>\"+array[1]+\"</option>\");\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t      //값이 없을때 처리 \r\n");
      out.write("\t\t\t\t\t\t$(\"#floorCd\").empty();\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t    }else {\r\n");
      out.write("\t\t\t    \tif (any_empt_line_span(\"bas_kiosk_add\", \"centerCd\", \"지점을 선택해주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfn_CheckForm  : function () {\r\n");
      out.write("\t\t\t\tif (any_empt_line_span(\"bas_kiosk_add\", \"ticketMchnSno\", \"무인발권기 Serial 입력해주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t\t\t\tif ($(\"#mode\").val() == \"Ins\" && $(\"#idCheck\").val() != \"Y\"){\r\n");
      out.write("\t\t\t\t\t   if (any_empt_line_span(\"bas_kiosk_add\", \"ticketMchnSno\", \"중복체크가 안되었습니다.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (any_empt_line_span(\"bas_kiosk_add\", \"centerCd\", \"지점을 선택해주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t\t\t\tif (any_empt_line_span(\"bas_kiosk_add\", \"floorCd\", \"층수를 선택해주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t\t\t\tvar commentTxt = ($(\"#mode\").val() == \"Ins\") ?  \"등록 하시겠습니까?\" : \"수정 하시겠습니까?\" ;\r\n");
      out.write("\t\t\t    $(\"#id_ConfirmInfo\").attr(\"href\", \"javascript:jqGridFunc.fn_update()\");\r\n");
      out.write("\t       \t\tfn_ConfirmPop(commentTxt);\r\n");
      out.write("\t\t  \t},\r\n");
      out.write("\t\t  \tfn_update: function(){\r\n");
      out.write("\t\t  \t    $(\"#confirmPage\").bPopup().close();\r\n");
      out.write("\t\t\t\tvar url = \"/backoffice/bas/kioskUpdate.do\";\r\n");
      out.write("\t\t\t\tvar params = \r\n");
      out.write("\t\t\t\t{ \t\r\n");
      out.write("\t\t\t\t\t'ticketMchnSno' : $(\"#ticketMchnSno\").val(),\r\n");
      out.write("\t\t\t\t\t'targetTicketMchnSno' : $(\"#targetTicketMchnSno\").val(),\r\n");
      out.write("\t\t\t\t\t'centerCd' : $(\"#centerCd\").val(),\r\n");
      out.write("\t\t\t\t\t'floorCd' : $(\"#floorCd\").val(),\r\n");
      out.write("\t\t\t\t\t'useYn' : $(\"input:radio[name='useYn']:checked\").val(),\r\n");
      out.write("\t\t\t\t\t'ticketMchnRemark' : $(\"#ticketMchnRemark\").val(),\r\n");
      out.write("\t\t\t\t\t'mode' : $(\"#mode\").val()\r\n");
      out.write("\t\t\t\t}; \r\n");
      out.write("\t\t\t\tfn_Ajax\r\n");
      out.write("\t\t\t\t(\r\n");
      out.write("\t\t\t\t\turl,\r\n");
      out.write("\t\t\t\t\t\"POST\",\r\n");
      out.write("\t\t\t\t\tparams,\r\n");
      out.write("\t\t\t\t\tfalse,\r\n");
      out.write("\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t\t\t\t\t\t\tcommon_popup(result.message, \"Y\",\"bas_kiosk_add\");\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href=\"/backoffice/login.do\";\r\n");
      out.write("\t\t\t\t\t\t} else if (result.status == \"OVERLAP FAIL\"){\r\n");
      out.write("\t\t\t\t\t\t\tcommon_popup(result.message, \"Y\", \"bas_kiosk_add\");\r\n");
      out.write("\t\t\t\t\t\t} else if (result.status == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\tcommon_modelCloseM(result.message, \"bas_kiosk_add\");\r\n");
      out.write("\t\t\t\t\t\t\tjqGridFunc.fn_search();\r\n");
      out.write("\t\t\t\t\t\t}else if (result.status == \"FAIL\"){\r\n");
      out.write("\t   \t\t\t\t\t\t   common_popup(result.message, \"Y\", \"bas_kiosk_add\");\r\n");
      out.write("\t   \t\t\t\t\t\t   jqGridFunc.fn_search();\r\n");
      out.write("\t   \t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tfunction(request){\r\n");
      out.write("\t\t\t\t\t\tcommon_modelCloseM(\"Error:\" + request.status,\"bas_kiosk_add\");\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t  \t},\r\n");
      out.write("\t\t\tfn_search: function(){\r\n");
      out.write("\t\t\t\t$(\"#mainGrid\").setGridParam({\r\n");
      out.write("\t\t\t\t\tdatatype : \"json\",\r\n");
      out.write("\t\t\t\t\tpostData : JSON.stringify({\r\n");
      out.write("\t\t\t\t\t\t\"pageIndex\": $(\"#pager .ui-pg-input\").val(),\r\n");
      out.write("\t\t\t\t\t\t\"searchKeyword\" : $(\"#searchKeyword\").val(),\r\n");
      out.write("\t\t\t\t\t\t\"searchCenterCd\" : $(\"#searchCenterCd\").val(),\r\n");
      out.write("\t\t\t\t\t\t\"pageUnit\":$('.ui-pg-selbox option:selected').val()\r\n");
      out.write("\t\t\t\t\t}),\r\n");
      out.write("\t\t\t\t\tloadComplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}).trigger(\"reloadGrid\");\r\n");
      out.write("\t \t\t}, \r\n");
      out.write("\t\t\tfn_idCheck : function(){\r\n");
      out.write("\t\t\t\tif (any_empt_line_span(\"bas_kiosk_add\", \"ticketMchnSno\", \"무인발권기 Serial을 입력해 주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t        \tvar url = \"/backoffice/bas/kisokSerialCheck.do\"\r\n");
      out.write("    \t        var param =  {\"ticketMchnSno\" : $(\"#ticketMchnSno\").val()};\r\n");
      out.write("\r\n");
      out.write("\t        \tfn_Ajax(url, \"GET\", param, false,\r\n");
      out.write("        \t\t\t    function(result) {\t\r\n");
      out.write("     \t\t\t           if (result != null) {\t       \t\r\n");
      out.write("     \t\t\t        \t   if (result.status == \"SUCCESS\"){\r\n");
      out.write("     \t\t\t        \t\t    var message = result.result == \"OK\" ? '등록되지 않은 발권기 입니다.' : '등록된 발권기 입니다.';\r\n");
      out.write("     \t\t\t        \t\t    var alertIcon =  result.result == \"OK\" ? \"Y\" : \"N\";\r\n");
      out.write("     \t\t\t        \t\t    \r\n");
      out.write("     \t\t\t        \t\t    common_popup(message, alertIcon, \"bas_kiosk_add\");\r\n");
      out.write("    \t\t\t        \t\t    $(\"#idCheck\").val(alertIcon);\r\n");
      out.write("\t\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcommon_popup('");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("', \"N\", \"bas_kiosk_add\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#idCheck\").val(\"N\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tcommon_modelCloseM(result.message,\"bas_kiosk_add\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t    function(request){\r\n");
      out.write("\t\t\t\t\t\t\tcommon_popup('");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("', \"N\", \"bas_kiosk_add\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#idCheck\").val(\"N\");\t       \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t    }    \t\t\r\n");
      out.write("\t\t        ); \r\n");
      out.write("\t\t\t}   \r\n");
      out.write("    \t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(371,23) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("common.codeFail.msg");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f1_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent(null);
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(380,21) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("common.codeFail.msg");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
      _jspx_th_spring_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(390,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("regist");
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(390,0) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("regist");
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(390,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(390,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("/backoffice/bas/kioskList.do");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<div id=\"wrapper\">\t\r\n");
            out.write("\t\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fimport_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t<input type=\"hidden\" name=\"mode\" id=\"mode\" >\r\n");
            out.write("\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t<div id=\"contents\">\r\n");
            out.write("    \t\t<div class=\"breadcrumb\">\r\n");
            out.write("      \t\t\t<ol class=\"breadcrumb-item\">\r\n");
            out.write("        \t\t\t<li>기초 관리</li>\r\n");
            out.write("       \t\t\t\t<li class=\"active\">　> 무인발권기 관리</li>\r\n");
            out.write("      \t\t\t</ol>\r\n");
            out.write("    \t\t</div>\r\n");
            out.write("    \t\t\r\n");
            out.write("    \t\t<h2 class=\"title\">무인발권기 관리</h2>\r\n");
            out.write("    \t\t<div class=\"clear\">\r\n");
            out.write("    \t</div>\r\n");
            out.write("    \t<div class=\"dashboard\">\r\n");
            out.write("        <!--contents-->\r\n");
            out.write("        \t<div class=\"boardlist\">\r\n");
            out.write("       <!--// search -->\r\n");
            out.write("\t          \t<div class=\"whiteBox searchBox\">\r\n");
            out.write("\t                <div class=\"sName\">\r\n");
            out.write("\t                  <h3>옵션 선택</h3>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t                <div class=\"top\">\r\n");
            out.write("\t                    <p>검색어</p>\r\n");
            out.write("\t                    <select name=\"searchCenterCd\" id=\"searchCenterCd\"->\r\n");
            out.write("\t\t\t\t\t\t\t<option value=\"\">지점 선택</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforEach_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t        </select>\r\n");
            out.write("\t                    <select id=\"searchCondition\" name=\"searchCondition\">\r\n");
            out.write("\t                        <option value=\"ALL\">전체</option>\r\n");
            out.write("\t\t\t\t\t\t\t<option value=\"CENTER_NM\">지점명</option>\r\n");
            out.write("\t\t\t\t\t\t\t<option value=\"FLOOR_NM\">사용층수</option>\r\n");
            out.write("\t                    </select>\r\n");
            out.write("\t                    <input type=\"text\" name=\"searchKeyword\" id=\"searchKeyword\"   placeholder=\"검색어를 입력하새요.\">\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t                <div class=\"inlineBtn \">\r\n");
            out.write("\t                    <a href=\"javascript:jqGridFunc.fn_search();\" class=\"grayBtn\">검색</a>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t            <div class=\"left_box mng_countInfo\">\r\n");
            out.write("\t              <p>총 : <span id=\"sp_totcnt\"></span>건</p>\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t            <div class=\"right_box\">\r\n");
            out.write("\t                <a href=\"#\" class=\"blueBtn\" onclick=\"jqGridFunc.fn_kioskInfo('Ins','')\">무인발권기 등록</a>\r\n");
            out.write("\t                <a href=\"#\" onClick=\"jqGridFunc.fn_delCheck()\" class=\"grayBtn\">삭제</a>\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t            <div class=\"clear\"></div>\r\n");
            out.write("\t            <div class=\"whiteBox\"></div>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("        <div class=\"Swrap tableArea\">\r\n");
            out.write("\t\t\t<table id=\"mainGrid\">\r\n");
            out.write("\t\t\t</table>\r\n");
            out.write("\t\t\t<div id=\"pager\" class=\"scroll\" style=\"text-align:center;\"></div>     \r\n");
            out.write("\t\t\t<br />\r\n");
            out.write("\t\t\t<div id=\"paginate\"></div>   \r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- 무인발권기 정보 추가 팝업-->\r\n");
            out.write("\t<div id=\"bas_kiosk_add\" class=\"popup m_pop\">\r\n");
            out.write("\t\t<div class=\"pop_con\">\r\n");
            out.write("\t\t\t<a class=\"button b-close\">X</a>\r\n");
            out.write("        \t<h2 class=\"pop_tit\">무인발권기 등록</h2>\r\n");
            out.write("        \t<div class=\"pop_wrap\">\r\n");
            out.write("        \t\t<table class=\"detail_table\">\r\n");
            out.write("               \t\t<tbody>\r\n");
            out.write("                   \t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<th>무인발권기 Serial</th>\r\n");
            out.write("\t\t                    <td>\r\n");
            out.write("\t\t                    \t<input type=\"text\" name=\"ticketMchnSno\" id=\"ticketMchnSno\">\r\n");
            out.write("\t\t                    \t<span id=\"sp_Unqi\">\r\n");
            out.write("                                <a href=\"javascript:jqGridFunc.fn_idCheck()\" class=\"blueBtn\">중복확인</a>\r\n");
            out.write("                                <input type=\"hidden\" id=\"idCheck\">\r\n");
            out.write("                                </span>\r\n");
            out.write("\t\t                    </td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t        <th>지점명</th>\r\n");
            out.write("\t\t\t\t            <td>\r\n");
            out.write("\t\t\t\t            \t<select name=\"centerCd\" id=\"centerCd\" onchange=\"jqGridFunc.fn_floorCombo()\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">지점 선택</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t                 </select>\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t        <th>층수</th>\r\n");
            out.write("\t\t\t\t            <td>\r\n");
            out.write("\t\t\t\t            \t\r\n");
            out.write("\t\t\t\t\t\t\t\t<select name=\"floorCd\" id=\"floorCd\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t</select>\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<th>사용 유무</th>\r\n");
            out.write("\t\t\t\t\t\t    <td>\r\n");
            out.write("\t\t\t\t\t            <span>\r\n");
            out.write("\t\t\t\t                    <input type=\"radio\" name=\"useYn\" id=\"useY\" value=\"Y\" checked=\"checked\">\r\n");
            out.write("\t\t\t\t                    <label for=\"y\">사용</label>\r\n");
            out.write("\t\t\t\t\t\t\t\t</span>\r\n");
            out.write("\t\t\t\t\t\t\t    <span>\r\n");
            out.write("\t\t\t\t\t\t            <input type=\"radio\" name=\"useYn\" id=\"useN\" value=\"N\">\r\n");
            out.write("\t\t\t\t\t                <label for=\"n\">사용 안함</label>\r\n");
            out.write("\t\t\t\t                </span>\r\n");
            out.write("\t\t\t                </td>\r\n");
            out.write("\t\t                </tr>\r\n");
            out.write("\t                    <tr>\r\n");
            out.write("\t                    \t<th>설명</th>\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t        <textarea name=\"ticketMchnRemark\" id=\"ticketMchnRemark\" rows=\"5\"></textarea>\r\n");
            out.write("\t\t\t\t\t        </td>\r\n");
            out.write("\t\t\t\t        </tr>\r\n");
            out.write("\t\t\t\t\t</tbody>\r\n");
            out.write("\t\t\t\t</table>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t    <div class=\"right_box\">\r\n");
            out.write("\t        \t<a href=\"#\" onClick=\"common_modelClose('bas_kiosk_add')\" class=\"grayBtn b-close\">취소</a>\r\n");
            out.write("\t\t\t    <a href=\"javascript:jqGridFunc.fn_CheckForm();\" id=\"btnSave\" class=\"blueBtn\">저장</a>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t\t<div class=\"clear\"></div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t");
            if (_jspx_meth_c_005fimport_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t<script type=\"text/javascript\" src=\"/resources/js/back_common.js\"></script>\r\n");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(393,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/backoffice/inc/top_inc.do");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(420,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/backoffice/bas/kioskList.jsp(420,7) '${centerInfo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${centerInfo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(420,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("centerInfo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerInfo.center_cd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerInfo.center_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(482,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/backoffice/bas/kioskList.jsp(482,9) '${centerInfo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${centerInfo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(482,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("centerInfo");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerInfo.center_cd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${centerInfo.center_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bas/kioskList.jsp(526,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/backoffice/inc/popup_common.do");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
