/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-11-30 08:23:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backoffice.bas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class progrmList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no;\" />\r\n");
      out.write("    <title>경륜경정 스마트입장 관리자</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/reset.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/paragraph.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/toggle.css\">\r\n");
      out.write("    <script src=\"/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/bpopup.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\tjQuery.browser = {};\r\n");
      out.write("\t(function () {\r\n");
      out.write("\t    jQuery.browser.msie = false;\r\n");
      out.write("\t    jQuery.browser.version = 0;\r\n");
      out.write("\t    if (navigator.userAgent.match(/MSIE ([0-9]+)\\./)) {\r\n");
      out.write("\t        jQuery.browser.msie = true;\r\n");
      out.write("\t        jQuery.browser.version = RegExp.$1;\r\n");
      out.write("\t    }\r\n");
      out.write("\t})();\r\n");
      out.write("\t</script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/jquery-ui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/jqgrid/src/css/ui.jqgrid.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/src/i18n/grid.locale-kr.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/jqgrid/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/js/xlsx.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/xlsx.full.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" language=\"javascript\" src=\"/resources/js/jszip.min.js\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("     .ui-jqgrid .ui-jqgrid-htable th div{\r\n");
      out.write("\t\toutline-style: none;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t }\r\n");
      out.write("     .ui-jqgrid tr.jqgrow {\r\n");
      out.write("\t\toutline-style: none;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() { \r\n");
      out.write("\t\t   jqGridFunc.setGrid(\"mainGrid\");\r\n");
      out.write("\t });\r\n");
      out.write("    var jqGridFunc  = {\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tsetGrid : function(gridOption){\r\n");
      out.write("    \t\t\tvar grid = $('#'+gridOption);\r\n");
      out.write("    \t\t    var postData = {\"pageIndex\": \"1\"};\r\n");
      out.write("    \t\t    grid.jqGrid({\r\n");
      out.write("    \t\t    \turl : '/backoffice/bas/progrmListAjax.do' ,\r\n");
      out.write("    \t\t        mtype :  'POST',\r\n");
      out.write("    \t\t        datatype :'json',\r\n");
      out.write("    \t\t        pager: $('#pager'),  \r\n");
      out.write("    \t\t        ajaxGridOptions: { contentType: \"application/json; charset=UTF-8\" },\r\n");
      out.write("    \t\t        ajaxRowOptions: { contentType: \"application/json; charset=UTF-8\", async: true },\r\n");
      out.write("    \t\t        ajaxSelectOptions: { contentType: \"application/json; charset=UTF-8\", dataType: \"JSON\" }, \r\n");
      out.write("    \t\t       \r\n");
      out.write("    \t\t        postData :  JSON.stringify( postData ),\r\n");
      out.write("    \t\t        jsonReader : {\r\n");
      out.write("\t   \t\t             root : 'resultlist',\r\n");
      out.write("\t   \t\t             \"page\":\"paginationInfo.currentPageNo\",\r\n");
      out.write("\t   \t\t             \"total\":\"paginationInfo.totalPageCount\",\r\n");
      out.write("\t   \t\t             \"records\":\"paginationInfo.totalRecordCount\",\r\n");
      out.write("\t   \t\t             repeatitems:false\r\n");
      out.write("   \t\t            },\r\n");
      out.write("    \t\t        colModel :  [\r\n");
      out.write("\t    \t\t \t                { label: '프로그램 파일명',  name:'progrm_file_nm',         index:'progrm_file_nm',        align:'left',   width:'10%'},\r\n");
      out.write("\t    \t\t \t                { label: '프로그램명',  name:'progrm_koreannm',         index:'progrm_koreannm',        align:'left',   width:'10%'},\r\n");
      out.write("\t    \t\t \t                { label: 'URL',  name:'url',         index:'url',        align:'left',   width:'10%'},\r\n");
      out.write("\t    \t\t \t                { label: '프로그램설명', name:'progrm_dc', index:'progrm_dc', align:'center', width:'12%'},\r\n");
      out.write("\t      \t\t\t                { label: '삭제', name: 'btn',  index:'btn',      align:'center',  width: 50, fixed:true, sortable : \r\n");
      out.write("\t    \t\t\t                  false, formatter:jqGridFunc.rowBtn}\r\n");
      out.write("    \t\t\t                ],  //상단면 \r\n");
      out.write("    \t\t        rowNum : 10,  //레코드 수\r\n");
      out.write("    \t\t        rowList : [10,20,30,40,50,100],  // 페이징 수\r\n");
      out.write("    \t\t        pager : pager,\r\n");
      out.write("    \t\t        refresh : true,\r\n");
      out.write("    \t            rownumbers : false, // 리스트 순번\r\n");
      out.write("    \t\t        viewrecord : true,    // 하단 레코드 수 표기 유무\r\n");
      out.write("    \t\t        loadonce : false,     // true 데이터 한번만 받아옴 \r\n");
      out.write("    \t\t        loadui : \"enable\",\r\n");
      out.write("    \t\t        loadtext:'데이터를 가져오는 중...',\r\n");
      out.write("    \t\t        emptyrecords : \"조회된 데이터가 없습니다\", //빈값일때 표시 \r\n");
      out.write("    \t\t        height : \"100%\",\r\n");
      out.write("    \t\t        autowidth:true,\r\n");
      out.write("    \t\t        shrinkToFit : true,\r\n");
      out.write("    \t\t        refresh : true,\r\n");
      out.write("    \t\t        loadComplete : function (data){\r\n");
      out.write("    \t\t        \t $(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);\r\n");
      out.write("    \t\t        },loadError:function(xhr, status, error) {\r\n");
      out.write("    \t\t            alert(error); \r\n");
      out.write("    \t\t        }, onPaging: function(pgButton){\r\n");
      out.write("    \t\t        \t  var gridPage = grid.getGridParam('page'); //get current  page\r\n");
      out.write("    \t\t        \t  var lastPage = grid.getGridParam(\"lastpage\"); //get last page \r\n");
      out.write("    \t\t        \t  var totalPage = grid.getGridParam(\"total\");\r\n");
      out.write("    \t\t              if (pgButton == \"next\"){\r\n");
      out.write("    \t\t            \t  if (gridPage < lastPage ){\r\n");
      out.write("    \t\t            \t\t  gridPage += 1;\r\n");
      out.write("    \t\t            \t  }else{\r\n");
      out.write("    \t\t            \t\t  gridPage = gridPage;\r\n");
      out.write("    \t\t            \t  }\r\n");
      out.write("    \t\t              }else if (pgButton == \"prev\"){\r\n");
      out.write("    \t\t            \t  if (gridPage > 1 ){\r\n");
      out.write("    \t\t            \t\t  gridPage -= 1;\r\n");
      out.write("    \t\t            \t  }else{\r\n");
      out.write("    \t\t            \t\t  gridPage = gridPage;\r\n");
      out.write("    \t\t            \t  }\r\n");
      out.write("    \t\t              }else if (pgButton == \"first\"){\r\n");
      out.write("    \t\t            \t  gridPage = 1;\r\n");
      out.write("    \t\t              }else if  ( pgButton == \"last\"){\r\n");
      out.write("    \t\t            \t  gridPage = lastPage;\r\n");
      out.write("    \t\t              } else if (pgButton == \"user\"){\r\n");
      out.write("    \t\t            \t  var nowPage = Number($(\"#pager .ui-pg-input\").val());\r\n");
      out.write("    \t\t            \t  \r\n");
      out.write("    \t\t            \t  if (totalPage >= nowPage && nowPage > 0 ){\r\n");
      out.write("    \t\t            \t\t  gridPage = nowPage;\r\n");
      out.write("    \t\t            \t  }else {\r\n");
      out.write("    \t\t            \t\t  $(\"#pager .ui-pg-input\").val(nowPage);\r\n");
      out.write("    \t\t            \t\t  gridPage = nowPage;\r\n");
      out.write("    \t\t            \t  }\r\n");
      out.write("    \t\t              }else if (pgButton == \"records\"){\r\n");
      out.write("    \t\t            \t  gridPage = 1;\r\n");
      out.write("    \t\t              }\r\n");
      out.write("    \t\t              grid.setGridParam({\r\n");
      out.write("\t\t    \t\t          \t  page : gridPage,\r\n");
      out.write("\t\t    \t\t          \t  rowNum : $('.ui-pg-selbox option:selected').val(),\r\n");
      out.write("\t\t    \t\t          \t  postData : JSON.stringify(  {\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t          \t\t\t\"pageIndex\": gridPage,\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t          \t\t\t\"searchKeyword\" : $(\"#searchKeyword\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t          \t\t\t\"pageUnit\":$('.ui-pg-selbox option:selected').val()\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t          \t\t})\r\n");
      out.write("    \t\t          \t\t}).trigger(\"reloadGrid\");\r\n");
      out.write("    \t\t        },onSelectRow: function(rowId){\r\n");
      out.write("    \t                if(rowId != null) {  }// 체크 할떄\r\n");
      out.write("    \t            },ondblClickRow : function(rowid, iRow, iCol, e){\r\n");
      out.write("    \t            \tgrid.jqGrid('editRow', rowid, {keys: true});\r\n");
      out.write("    \t            },onCellSelect : function (rowid, index, contents, action){\r\n");
      out.write("    \t            \tvar cm = $(this).jqGrid('getGridParam', 'colModel');\r\n");
      out.write("    \t                //console.log(cm);\r\n");
      out.write("    \t                if (cm[index].name !='btn'){\r\n");
      out.write("    \t                \tjqGridFunc.fn_ProgramInfo(\"Edt\", $(this).jqGrid('getCell', rowid, 'progrm_file_nm'));\r\n");
      out.write("            \t\t    }\r\n");
      out.write("    \t            }\r\n");
      out.write("    \t\t    });\r\n");
      out.write("    \t\t}, rowBtn: function (cellvalue, options, rowObject){\r\n");
      out.write("               if (rowObject.progrm_file_nm != \"\")\r\n");
      out.write("            \t   return \"<a href='javascript:jqGridFunc.delRow(\\\"\"+rowObject.progrm_file_nm+\"\\\");'>삭제</a>\";\r\n");
      out.write("            }, refreshGrid : function(){\r\n");
      out.write("\t           $('#mainGrid').jqGrid().trigger(\"reloadGrid\");\r\n");
      out.write("\t        }, fn_search: function(){\r\n");
      out.write("\t    \t   $(\"#mainGrid\").setGridParam({\r\n");
      out.write("\t    \t    \t datatype\t: \"json\",\r\n");
      out.write("\t    \t    \t postData\t: JSON.stringify(  {\r\n");
      out.write("\t    \t    \t\t\"pageIndex\": $(\"#pager .ui-pg-input\").val(),\r\n");
      out.write("\t         \t\t\t\"searchKeyword\" : $(\"#searchKeyword\").val(),\r\n");
      out.write("\t         \t\t\t\"pageUnit\":$('.ui-pg-selbox option:selected').val()\r\n");
      out.write("\t         \t\t}),\r\n");
      out.write("\t    \t    \tloadComplete\t: function(data) {$(\"#sp_totcnt\").text(data.paginationInfo.totalRecordCount);}\r\n");
      out.write("\t    \t     }).trigger(\"reloadGrid\");\r\n");
      out.write(" \r\n");
      out.write("\t        }, delRow : function (progrmFileNm){\r\n");
      out.write("\t        \tif(progrmFileNm != \"\") {\r\n");
      out.write("\t        \t\t   $(\"#hid_DelCode\").val(progrmFileNm)\r\n");
      out.write("\t \t\t\t\t   $(\"#id_ConfirmInfo\").attr(\"href\", \"javascript:jqGridFunc.fn_del()\");\r\n");
      out.write("\t        \t\t   fn_ConfirmPop(\"삭제 하시겠습니까?\");\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("            }, fn_del: function (){\r\n");
      out.write("\t\t\t     var params = {'progrmFileNm': $(\"#hid_DelCode\").val() };\r\n");
      out.write("\t\t\t     fn_uniDelAction(\"/backoffice/bas/programeDelete.do\",\"GET\", params, false, \"jqGridFunc.fn_search\");\r\n");
      out.write("   \t\t      \r\n");
      out.write("\t\t    }, clearGrid : function() {\r\n");
      out.write("                $(\"#mainGrid\").clearGridData();\r\n");
      out.write("            }, fn_ProgramInfo : function (mode, progrmFileNm){\r\n");
      out.write("            \t$(\"#mode\").val(mode);\r\n");
      out.write("        \t    if (mode == \"Edt\"){\r\n");
      out.write("\t\t        \t$(\"#progrmFileNm\").val(progrmFileNm).prop('readonly', true);\r\n");
      out.write("\t\t        \t$(\"#btnUpdate\").text(\"수정\");\r\n");
      out.write("\t\t        \tvar params = {\"progrmFileNm\" : progrmFileNm};\r\n");
      out.write("\t\t        \tvar url = \"/backoffice/bas/programeDetail.do\";\r\n");
      out.write("\t\t        \tfn_Ajax(url, \"GET\", params, false,\r\n");
      out.write("\t\t\t          \t    function(result) {\r\n");
      out.write("\t\t        \t\t       if (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t     \t\t\t\t    \t   common_modelCloseM(result.meesage, \"Y\", \"bas_code_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   location.href=\"/backoffice/login.do\";\r\n");
      out.write("\t       \t\t\t\t\t   }else if (result.status == \"SUCCESS\"){\r\n");
      out.write("       \t\t\t\t\t\t       var obj  = result.regist;\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#progrmStrePath\").val(obj.progrm_stre_path);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#progrmKoreannm\").val(obj.progrm_koreannm);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#progrmDc\").val(obj.progrm_dc);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#url\").val(obj.url);\r\n");
      out.write("       \t\t\t\t\t\t       $(\"#btnSave\").text(\"수정\");\r\n");
      out.write("\t       \t\t\t\t\t   }else{\r\n");
      out.write("\t       \t\t\t\t\t\t   common_modelCloseM(result.message,\"bas_code_add\");\r\n");
      out.write("\t       \t\t\t\t\t   }\r\n");
      out.write("\t\t\t     \t\t\t},\r\n");
      out.write("\t\t\t     \t\t\tfunction(request){\r\n");
      out.write("\t\t\t     \t\t\t     \r\n");
      out.write("\t\t\t     \t\t\t     common_modelCloseM(\"Error:\" + request.status,\"bas_code_add\");\r\n");
      out.write("\t\t\t     \t\t\t}\r\n");
      out.write("\t\t               );\r\n");
      out.write("\t\t        }else{\r\n");
      out.write("\t\t        \t$(\"#progrmFileNm\").val('').prop('readonly', false);\r\n");
      out.write("\t\t        \t$(\"#progrmStrePath\").val('');\r\n");
      out.write("\t\t        \t$(\"#progrmKoreannm\").val('');\r\n");
      out.write("\t\t        \t$(\"#progrmDc\").val('');\r\n");
      out.write("\t\t        \t$(\"#url\").val('');\r\n");
      out.write("\t\t        \t$(\"#btnUpdate\").text(\"입력\");\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t        $(\"#bas_program_add\").bPopup();\r\n");
      out.write("           },fn_CheckForm  : function (){\r\n");
      out.write("        \t   if (any_empt_line_span(\"bas_program_add\", \"progrmFileNm\", \"프로그램를 입력해 주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("        \t   if (any_empt_line_span(\"bas_program_add\", \"progrmKoreannm\", \"프로그램 명을 입력해 주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t\t\t   if (any_empt_line_span(\"bas_program_add\", \"url\", \"url을 입력해 주세요.\",\"sp_message\", \"savePage\") == false) return;\r\n");
      out.write("\t\t\t   var commentTxt = ($(\"#mode\").val() == \"Ins\") ?  \"등록 하시겠습니까?\" : \"수정 하시겠습니까?\" ;\r\n");
      out.write("\t\t       $(\"#id_ConfirmInfo\").attr(\"href\", \"javascript:jqGridFunc.fn_update()\");\r\n");
      out.write("       \t\t   fn_ConfirmPop(commentTxt);\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t  }, fn_update : function(){\r\n");
      out.write("\t\t\t  $(\"#confirmPage\").bPopup().close();\r\n");
      out.write("\t\t\t  var url = \"/backoffice/bas/programeUpdate.do\";\r\n");
      out.write("\t\t      var params = {    'progrmFileNm' : $(\"#progrmFileNm\").val(),\r\n");
      out.write("\t\t\t\t    \t\t     'progrmStrePath' : $(\"#progrmStrePath\").val(),\r\n");
      out.write("\t\t\t\t    \t\t     'progrmKoreannm' : $(\"#progrmKoreannm\").val(),\r\n");
      out.write("\t\t\t\t    \t\t     'progrmDc' : $(\"#progrmDc\").val(),\r\n");
      out.write("\t\t\t\t    \t\t     'url' : $(\"#url\").val(), \r\n");
      out.write("\t\t\t\t    \t\t     'mode' : $(\"#mode\").val()\r\n");
      out.write("\t\t    \t               }; \r\n");
      out.write("\t\t      fn_Ajax(url, \"POST\", params, false,\r\n");
      out.write("\t\t      \t\t\tfunction(result) {\r\n");
      out.write("\t\t    \t               if (result.status == \"LOGIN FAIL\"){\r\n");
      out.write("\t\t \t\t\t\t    \t   common_popup(result.meesage, \"Y\",\"bas_program_add\");\r\n");
      out.write("\t\t \t\t\t\t    \t   location.href=\"/backoffice/login.do\";\r\n");
      out.write("\t\t   \t\t\t\t\t   }else if (result.status == \"OVERLAP FAIL\" ){\r\n");
      out.write("\t\t   \t\t\t\t\t\t   common_popup(result.message,\"N\", \"bas_program_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   jqGridFunc.fn_search();\r\n");
      out.write("\t\t   \t\t\t\t\t   }else if (result.status == \"SUCCESS\"){\r\n");
      out.write("\t\t   \t\t\t\t\t\t   //총 게시물 정리 하기'\r\n");
      out.write("\t\t   \t\t\t\t\t\t   common_modelCloseM(\"정상적으로 저장 되었습니다.\",\"bas_program_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   jqGridFunc.fn_search();\r\n");
      out.write("\t\t   \t\t\t\t\t   }else {\r\n");
      out.write("\t\t   \t\t\t\t\t\t   common_popup(result.meesage, \"N\", \"bas_program_add\");\r\n");
      out.write("\t\t   \t\t\t\t\t\t   jqGridFunc.fn_search();\r\n");
      out.write("\t\t   \t\t\t\t\t   }\r\n");
      out.write("\t\t \t\t\t\t    },\r\n");
      out.write("\t\t \t\t\t\t    function(request){\r\n");
      out.write("\t\t \t\t\t\t    \tcommon_modelCloseM(\"Error:\" + request.status,\"bas_program_add\");\r\n");
      out.write("\t\t \t\t\t\t    }    \t\t\r\n");
      out.write("\t\t        );\r\n");
      out.write("\t\t}, fn_excelDown : function (cnt){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\".ui-pg-selbox\").val(100).trigger('change');\t\t\r\n");
      out.write(" \t\t\t$(\"#mainGrid\").jqGrid('setGridParam',{loadonce:true}).trigger('reloadGrid');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write(" \t\t\t$(\"#mainGrid\").jqGrid('exportToExcel',{\r\n");
      out.write("\t\t\t\tincludeLabels : true,\r\n");
      out.write("\t\t\t\tincludeGroupHeader : true,\r\n");
      out.write("\t\t\t\tincludeFooter: true,\r\n");
      out.write("\t\t\t\tfileName : \"jqGridExport.xlsx\",\r\n");
      out.write("\t\t\t\tmaxlength : 40 // maxlength for visible string data \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write("//\t\t\t$(\"#mainGrid\").jqGrid('setGridParam',{loadonce:false}).trigger('reloadGrid'); \r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/backoffice/bas/progrmList.jsp(281,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("regist");
      // /WEB-INF/jsp/backoffice/bas/progrmList.jsp(281,0) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("regist");
      // /WEB-INF/jsp/backoffice/bas/progrmList.jsp(281,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/jsp/backoffice/bas/progrmList.jsp(281,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("/backoffice/bas/msgList.do");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<input type=\"hidden\" id=\"mode\" name=\"mode\" />\r\n");
            out.write("<div class=\"wrapper\">\r\n");
            out.write("  <!--// header -->\r\n");
            out.write("  ");
            if (_jspx_meth_c_005fimport_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("  <!-- header //-->\r\n");
            out.write("  <!--// contents-->\r\n");
            out.write("  <div id=\"contents\">\r\n");
            out.write("    <div class=\"breadcrumb\">\r\n");
            out.write("      <ol class=\"breadcrumb-item\">\r\n");
            out.write("        <li>기초 관리</li>\r\n");
            out.write("        <li class=\"active\">　> 프로그램 관리</li>\r\n");
            out.write("      </ol>\r\n");
            out.write("    </div>\r\n");
            out.write("\r\n");
            out.write("    <h2 class=\"title\">프로그램 관리</h2><div class=\"clear\"></div>\r\n");
            out.write("    <!--// dashboard -->\r\n");
            out.write("    <div class=\"dashboard\">\r\n");
            out.write("        <!--contents-->\r\n");
            out.write("        <div class=\"boardlist\">\r\n");
            out.write("            <div class=\"left_box mng_countInfo\">\r\n");
            out.write("                <p>총 : <span id=\"sp_totcnt\"></span>건</p>\r\n");
            out.write("                \r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"right_box\">\r\n");
            out.write("\t\t\t\t<a id=\"export\" onClick=\"jqGridFunc.fn_excelDown()\" class=\"blueBtn\">엑셀 다운로드</a> \r\n");
            out.write("            \t<a href=\"#\" onClick=\"jqGridFunc.fn_ProgramInfo('Ins', '')\" class=\"blueBtn\">프로그램 추가</a>             \t\r\n");
            out.write("            </div>\r\n");
            out.write("             \r\n");
            out.write("            <div class=\"clear\"></div>\r\n");
            out.write("            <div class=\"whiteBox\">\r\n");
            out.write("                <table id=\"mainGrid\"></table>\r\n");
            out.write("                <div id=\"pager\" class=\"scroll\" style=\"text-align:center;\"></div>  \r\n");
            out.write("            </div>\r\n");
            out.write("            \r\n");
            out.write("        </div>\r\n");
            out.write("\r\n");
            out.write("    </div>\r\n");
            out.write("    \r\n");
            out.write("  </div>\r\n");
            out.write("  <!-- contents//-->\r\n");
            out.write("</div>\r\n");
            out.write("<!-- wrapper_end-->\r\n");
            out.write("<!-- popup -->\r\n");
            out.write("<!-- 프로그램 추가 팝업-->\r\n");
            out.write("<div id=\"bas_program_add\" class=\"popup m_pop\">\r\n");
            out.write("    <div class=\"pop_con\">\r\n");
            out.write("        <a class=\"button b-close\">X</a>\r\n");
            out.write("        <h2 class=\"pop_tit\">프로그램 등록</h2>\r\n");
            out.write("        <div class=\"pop_wrap\">\r\n");
            out.write("            <table class=\"detail_table\">\r\n");
            out.write("                <tbody>\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <th>프로그램 파일명</th>\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <input type=\"text\" id=\"progrmFileNm\" name=\"progrmFileNm\">\r\n");
            out.write("                        </td>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <th>지정 경로</th>\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <input type=\"text\" id=\"progrmStrePath\" name=\"progrmStrePath\">\r\n");
            out.write("                        </td>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <th>한글명</th>\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <input type=\"text\" id=\"progrmKoreannm\" name=\"progrmKoreannm\">\r\n");
            out.write("                        </td>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <th>URL</th>\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <input type=\"text\" id=\"url\" name=\"url\">\r\n");
            out.write("                        </td>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <th>설명</th>\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <textarea cols=\"25\" rows=\"5\" id=\"progrmDc\" name=\"progrmDc\"></textarea>\r\n");
            out.write("                        </td>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                </tbody>\r\n");
            out.write("            </table>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"right_box\">\r\n");
            out.write("            <a href=\"#\" onClick=\"common_modelClose('bas_program_add')\" class=\"grayBtn\">취소</a>\r\n");
            out.write("            <a href=\"#\" class=\"blueBtn\" onClick=\"jqGridFunc.fn_CheckForm()\" id=\"btnUpdate\" class=\"blueBtn\">저장</a>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"clear\"></div>\r\n");
            out.write("    </div>\r\n");
            out.write("</div>\r\n");
            out.write("     ");
            if (_jspx_meth_c_005fimport_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("    <script type=\"text/javascript\" src=\"/resources/js/common.js\"></script>\r\n");
            out.write("    <script type=\"text/javascript\" src=\"/resources/js/back_common.js\"></script>\r\n");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fcommandName_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bas/progrmList.jsp(285,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/backoffice/inc/top_inc.do");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/backoffice/bas/progrmList.jsp(373,5) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/backoffice/inc/popup_common.do");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
